// Code generated from api/specs; DO NOT EDIT.

package api

// OperationSummary maps operationId to a normalized CLI-friendly summary.
var OperationSummary = map[string]string{
	"Calendar":                                  "Get market calendar",
	"Clock":                                     "Get market clock",
	"CorporateActions":                          "Get corporate actions",
	"CryptoBars":                                "Get historical bars",
	"CryptoLatestBars":                          "Get latest bars",
	"CryptoLatestOrderbooks":                    "Get latest orderbook",
	"CryptoLatestQuotes":                        "Get latest quotes",
	"CryptoLatestTrades":                        "Get latest trades",
	"CryptoPerpLatestBars":                      "Get latest bars",
	"CryptoPerpLatestFuturesPricing":            "Get latest pricing",
	"CryptoPerpLatestOrderbooks":                "Get latest orderbook",
	"CryptoPerpLatestQuotes":                    "Get latest quotes",
	"CryptoPerpLatestTrades":                    "Get latest trades",
	"CryptoQuotes":                              "Get historical quotes",
	"CryptoSnapshots":                           "Get snapshots",
	"CryptoTrades":                              "Get historical trades",
	"FixedIncomeLatestPrices":                   "Get latest prices",
	"LatestRates":                               "Get latest rates for currency pairs",
	"LegacyCalendar":                            "Get US market calendar",
	"LegacyClock":                               "Get US market clock",
	"Logos":                                     "Get logos",
	"MostActives":                               "Get most active stocks",
	"Movers":                                    "Get top market movers",
	"News":                                      "Get news articles",
	"OptionChain":                               "Get option chain",
	"OptionLatestQuotes":                        "Get latest quotes",
	"OptionLatestTrades":                        "Get latest trades",
	"OptionMetaConditions":                      "Get condition codes",
	"OptionMetaExchanges":                       "Get exchange codes",
	"OptionSnapshots":                           "Get snapshots",
	"OptionTrades":                              "Get historical trades",
	"Rates":                                     "Get historical rates for currency pairs",
	"StockAuctionSingle":                        "Get historical auctions (single)",
	"StockAuctions":                             "Get historical auctions",
	"StockBarSingle":                            "Get historical bars (single symbol)",
	"StockBars":                                 "Get historical bars",
	"StockLatestBarSingle":                      "Get latest bar (single symbol)",
	"StockLatestBars":                           "Get latest bars",
	"StockLatestQuoteSingle":                    "Get latest quote (single symbol)",
	"StockLatestQuotes":                         "Get latest quotes",
	"StockLatestTradeSingle":                    "Get latest trade (single symbol)",
	"StockLatestTrades":                         "Get latest trades",
	"StockMetaConditions":                       "Get condition codes",
	"StockMetaExchanges":                        "Get exchange codes",
	"StockQuoteSingle":                          "Get historical quotes (single symbol)",
	"StockQuotes":                               "Get historical quotes",
	"StockSnapshotSingle":                       "Get snapshot (single symbol)",
	"StockSnapshots":                            "Get snapshots",
	"StockTradeSingle":                          "Get historical trades (single symbol)",
	"StockTrades":                               "Get historical trades",
	"UsCorporates":                              "Get US corporates",
	"UsTreasuries":                              "Get US treasuries",
	"addAssetToWatchlist":                       "Add asset to watchlist",
	"addAssetToWatchlistByName":                 "Add asset to watchlist by name",
	"createCryptoPerpTransferForAccount":        "Request a new withdrawal",
	"createCryptoTransferForAccount":            "Request a new withdrawal",
	"createWhitelistedAddress":                  "Request a new whitelisted address",
	"createWhitelistedPerpAddress":              "Request a new whitelisted address",
	"deleteAllOpenPositions":                    "Close all positions",
	"deleteAllOrders":                           "Delete all orders",
	"deleteOpenPosition":                        "Close a position",
	"deleteOrderByOrderID":                      "Delete order by ID",
	"deleteWatchlistById":                       "Delete watchlist by id",
	"deleteWatchlistByName":                     "Delete watchlist by name",
	"deleteWhitelistedAddress":                  "Delete a whitelisted address",
	"deleteWhitelistedPerpAddress":              "Delete a whitelisted address",
	"get-option-contract-symbol_or_id":          "Get an option contract by ID or symbol",
	"get-options-contracts":                     "Get option contracts",
	"get-v2-assets":                             "Get assets",
	"get-v2-assets-symbol_or_asset_id":          "Get an asset by ID or symbol",
	"get-v2-corporate_actions-announcements":    "Retrieve announcements",
	"get-v2-corporate_actions-announcements-id": "Retrieve a specific announcement",
	"getAccount":                                "Get account",
	"getAccountActivities":                      "Retrieve account activities",
	"getAccountActivitiesByActivityType":        "Retrieve account activities of specific type",
	"getAccountConfig":                          "Get account configurations",
	"getAccountPortfolioHistory":                "Get account portfolio history",
	"getAllOpenPositions":                       "List all open positions",
	"getAllOrders":                              "Get all orders",
	"getCryptoFundingTransfer":                  "Retrieve a crypto funding transfer",
	"getCryptoPerpAccountLeverage":              "Get account leverage for an asset",
	"getCryptoPerpAccountVitals":                "Retrieve account vitals",
	"getCryptoPerpFundingTransfer":              "Retrieve a crypto funding transfer",
	"getCryptoPerpTransferEstimate":             "Returns the estimated gas fee for a proposed transaction",
	"getCryptoTransferEstimate":                 "Returns the estimated gas fee for a proposed transaction",
	"getOpenPosition":                           "Get an open position",
	"getOrderByClientOrderId":                   "Get order by client order ID",
	"getOrderByOrderID":                         "Get order by ID",
	"getWatchlistById":                          "Get watchlist by ID",
	"getWatchlistByName":                        "Get watchlist by name",
	"getWatchlists":                             "Get all watchlists",
	"listCryptoFundingTransfers":                "Retrieve crypto funding transfers",
	"listCryptoFundingWallets":                  "Retrieve crypto funding wallets",
	"listCryptoPerpFundingTransfers":            "Retrieve crypto funding transfers",
	"listCryptoPerpFundingWallets":              "Retrieve crypto funding wallets",
	"listWhitelistedAddress":                    "List an array of whitelisted addresses",
	"listWhitelistedPerpAddress":                "List an array of whitelisted addresses",
	"optionBars":                                "Get historical bars",
	"optionDoNotExercise":                       "Do not exercise an options position",
	"optionExercise":                            "Exercise an options position",
	"patchAccountConfig":                        "Update account configurations",
	"patchOrderByOrderId":                       "Replace order by ID",
	"postOrder":                                 "Create an order",
	"postWatchlist":                             "Create watchlist",
	"removeAssetFromWatchlist":                  "Delete symbol from watchlist",
	"setCryptoPerpAccountLeverage":              "Set account leverage for an asset",
	"updateWatchlistById":                       "Update watchlist by id",
	"updateWatchlistByName":                     "Update watchlist by name",
}

// ParamDescription maps operationId.paramName to a normalized description.
var ParamDescription = map[string]string{
	"Calendar.end":                                        "last date to retrieve data for (inclusive). Default: one week from the start date",
	"Calendar.market":                                     "market",
	"Calendar.start":                                      "first date to retrieve data for (inclusive). Default: today",
	"Calendar.timezone":                                   "timezone of the times. Default: the timezone of the market",
	"Clock.markets":                                       "comma-separated list of markets",
	"Clock.time":                                          "instead of the current time, use this time for the clock",
	"CorporateActions.cusips":                             "A comma-separated list of CUSIPs",
	"CorporateActions.end":                                "inclusive end of the interval",
	"CorporateActions.ids":                                "A comma-separated list of corporate action IDs",
	"CorporateActions.limit":                              "maximum number of corporate actions to return in a response.",
	"CorporateActions.page_token":                         "pagination token from which to continue",
	"CorporateActions.sort":                               "sort data in ascending or descending order",
	"CorporateActions.start":                              "inclusive start of the interval",
	"CorporateActions.symbols":                            "A comma-separated list of symbols",
	"CorporateActions.types":                              "A comma-separated list of types",
	"CryptoBars.end":                                      "inclusive end of the interval",
	"CryptoBars.limit":                                    "maximum number of data points to return in the response page.",
	"CryptoBars.loc":                                      "crypto location from where the historical market data is retrieved.\n- us: Alpaca US\n- us-1: Kraken US\n- eu-1: Kraken EU",
	"CryptoBars.page_token":                               "pagination token from which to continue",
	"CryptoBars.sort":                                     "sort data in ascending or descending order",
	"CryptoBars.start":                                    "inclusive start of the interval",
	"CryptoBars.symbols":                                  "A comma-separated list of crypto symbols",
	"CryptoBars.timeframe":                                "timeframe represented by each bar in aggregation.\nYou can use any of the following values:\n - [1-59]Min or [1-59]T, e.g",
	"CryptoLatestBars.loc":                                "crypto location from where the latest market data is retrieved.\n- us: Alpaca US\n- us-1: Kraken US\n- eu-1: Kraken EU",
	"CryptoLatestBars.symbols":                            "A comma-separated list of crypto symbols",
	"CryptoLatestOrderbooks.loc":                          "crypto location from where the latest market data is retrieved.\n- us: Alpaca US\n- us-1: Kraken US\n- eu-1: Kraken EU",
	"CryptoLatestOrderbooks.symbols":                      "A comma-separated list of crypto symbols",
	"CryptoLatestQuotes.loc":                              "crypto location from where the latest market data is retrieved.\n- us: Alpaca US\n- us-1: Kraken US\n- eu-1: Kraken EU",
	"CryptoLatestQuotes.symbols":                          "A comma-separated list of crypto symbols",
	"CryptoLatestTrades.loc":                              "crypto location from where the latest market data is retrieved.\n- us: Alpaca US\n- us-1: Kraken US\n- eu-1: Kraken EU",
	"CryptoLatestTrades.symbols":                          "A comma-separated list of crypto symbols",
	"CryptoPerpLatestBars.loc":                            "crypto perpetual location",
	"CryptoPerpLatestBars.symbols":                        "A comma-separated list of crypto symbols",
	"CryptoPerpLatestFuturesPricing.loc":                  "crypto perpetual location",
	"CryptoPerpLatestFuturesPricing.symbols":              "A comma-separated list of crypto symbols",
	"CryptoPerpLatestOrderbooks.loc":                      "crypto perpetual location",
	"CryptoPerpLatestOrderbooks.symbols":                  "A comma-separated list of crypto symbols",
	"CryptoPerpLatestQuotes.loc":                          "crypto perpetual location",
	"CryptoPerpLatestQuotes.symbols":                      "A comma-separated list of crypto symbols",
	"CryptoPerpLatestTrades.loc":                          "crypto perpetual location",
	"CryptoPerpLatestTrades.symbols":                      "A comma-separated list of crypto symbols",
	"CryptoQuotes.end":                                    "inclusive end of the interval",
	"CryptoQuotes.limit":                                  "maximum number of data points to return in the response page.",
	"CryptoQuotes.loc":                                    "crypto location from where the historical market data is retrieved.\n- us: Alpaca US\n- us-1: Kraken US\n- eu-1: Kraken EU",
	"CryptoQuotes.page_token":                             "pagination token from which to continue",
	"CryptoQuotes.sort":                                   "sort data in ascending or descending order",
	"CryptoQuotes.start":                                  "inclusive start of the interval",
	"CryptoQuotes.symbols":                                "A comma-separated list of crypto symbols",
	"CryptoSnapshots.loc":                                 "crypto location from where the latest market data is retrieved.\n- us: Alpaca US\n- us-1: Kraken US\n- eu-1: Kraken EU",
	"CryptoSnapshots.symbols":                             "A comma-separated list of crypto symbols",
	"CryptoTrades.end":                                    "inclusive end of the interval",
	"CryptoTrades.limit":                                  "maximum number of data points to return in the response page.",
	"CryptoTrades.loc":                                    "crypto location from where the historical market data is retrieved.\n- us: Alpaca US\n- us-1: Kraken US\n- eu-1: Kraken EU",
	"CryptoTrades.page_token":                             "pagination token from which to continue",
	"CryptoTrades.sort":                                   "sort data in ascending or descending order",
	"CryptoTrades.start":                                  "inclusive start of the interval",
	"CryptoTrades.symbols":                                "A comma-separated list of crypto symbols",
	"FixedIncomeLatestPrices.isins":                       "A comma-separated list of ISINs with a limit of 1000",
	"LatestRates.currency_pairs":                          "currency pairs",
	"LegacyCalendar.date_type":                            "indicates what start and end mean",
	"LegacyCalendar.end":                                  "last date to retrieve data for (inclusive)",
	"LegacyCalendar.start":                                "first date to retrieve data for (inclusive)",
	"Logos.placeholder":                                   "placeholder",
	"Logos.symbol":                                        "A unique series of letters assigned to a security for trading purposes",
	"MostActives.by":                                      "metric used for ranking the most active stocks",
	"MostActives.top":                                     "number of top most active stocks to fetch per day",
	"Movers.market_type":                                  "screen-specific market (stocks or crypto)",
	"Movers.top":                                          "number of top market movers to fetch (gainers and losers)",
	"News.end":                                            "inclusive end of the interval",
	"News.exclude_contentless":                            "boolean indicator to exclude news articles that do not contain content",
	"News.include_content":                                "boolean indicator to include content for news articles (if available)",
	"News.limit":                                          "limit of news items to be returned for a result page",
	"News.page_token":                                     "pagination token from which to continue",
	"News.sort":                                           "sort articles by updated date",
	"News.start":                                          "inclusive start of the interval",
	"News.symbols":                                        "A comma-separated list of symbols for which to query news",
	"OptionChain.expiration_date":                         "filter contracts by the exact expiration date (format: YYYY-MM-DD)",
	"OptionChain.expiration_date_gte":                     "filter contracts with expiration date greater than or equal to the specified date",
	"OptionChain.expiration_date_lte":                     "filter contracts with expiration date less than or equal to the specified date",
	"OptionChain.feed":                                    "source feed of the data",
	"OptionChain.limit":                                   "number of maximum snapshots to return in a response.",
	"OptionChain.page_token":                              "pagination token from which to continue",
	"OptionChain.root_symbol":                             "filter contracts by the root symbol",
	"OptionChain.strike_price_gte":                        "filter contracts with strike price greater than or equal to the specified value",
	"OptionChain.strike_price_lte":                        "filter contracts with strike price less than or equal to the specified value",
	"OptionChain.type":                                    "filter contracts by the type (call or put)",
	"OptionChain.underlying_symbol":                       "financial instrument on which an option contract is based or derived",
	"OptionChain.updated_since":                           "filter to snapshots that were updated since this timestamp, meaning that the timestamp of the trade or the quote is g...",
	"OptionLatestQuotes.feed":                             "source feed of the data",
	"OptionLatestQuotes.symbols":                          "A comma-separated list of contract symbols with a limit of 100",
	"OptionLatestTrades.feed":                             "source feed of the data",
	"OptionLatestTrades.symbols":                          "A comma-separated list of contract symbols with a limit of 100",
	"OptionMetaConditions.ticktype":                       "type of ticks",
	"OptionSnapshots.feed":                                "source feed of the data",
	"OptionSnapshots.limit":                               "number of maximum snapshots to return in a response.",
	"OptionSnapshots.page_token":                          "pagination token from which to continue",
	"OptionSnapshots.symbols":                             "A comma-separated list of contract symbols with a limit of 100",
	"OptionSnapshots.updated_since":                       "filter to snapshots that were updated since this timestamp, meaning that the timestamp of the trade or the quote is g...",
	"OptionTrades.end":                                    "inclusive end of the interval",
	"OptionTrades.limit":                                  "maximum number of data points to return in the response page.",
	"OptionTrades.page_token":                             "pagination token from which to continue",
	"OptionTrades.sort":                                   "sort data in ascending or descending order",
	"OptionTrades.start":                                  "inclusive start of the interval",
	"OptionTrades.symbols":                                "A comma-separated list of contract symbols with a limit of 100",
	"Rates.currency_pairs":                                "currency pairs",
	"Rates.end":                                           "inclusive end of the interval",
	"Rates.limit":                                         "maximum number of data points to return in the response page.",
	"Rates.page_token":                                    "pagination token from which to continue",
	"Rates.sort":                                          "sort data in ascending or descending order",
	"Rates.start":                                         "inclusive start of the interval",
	"Rates.timeframe":                                     "timeframe",
	"StockAuctionSingle.asof":                             "as-of date of the queried stock symbol(s)",
	"StockAuctionSingle.currency":                         "currency of all prices in ISO 4217 format. Default: USD",
	"StockAuctionSingle.end":                              "inclusive end of the interval",
	"StockAuctionSingle.feed":                             "only sip is valid for auctions",
	"StockAuctionSingle.limit":                            "maximum number of data points to return in the response page.",
	"StockAuctionSingle.page_token":                       "pagination token from which to continue",
	"StockAuctionSingle.sort":                             "sort data in ascending or descending order",
	"StockAuctionSingle.start":                            "inclusive start of the interval",
	"StockAuctionSingle.symbol":                           "symbol to query",
	"StockAuctions.asof":                                  "as-of date of the queried stock symbol(s)",
	"StockAuctions.currency":                              "currency of all prices in ISO 4217 format. Default: USD",
	"StockAuctions.end":                                   "inclusive end of the interval",
	"StockAuctions.feed":                                  "only sip is valid for auctions",
	"StockAuctions.limit":                                 "maximum number of data points to return in the response page.",
	"StockAuctions.page_token":                            "pagination token from which to continue",
	"StockAuctions.sort":                                  "sort data in ascending or descending order",
	"StockAuctions.start":                                 "inclusive start of the interval",
	"StockAuctions.symbols":                               "A comma-separated list of stock symbols",
	"StockBarSingle.adjustment":                           "specifies the adjustments for the bars.\n\n - raw: no adjustments\n - split: adjust price and volume for forward and rev...",
	"StockBarSingle.asof":                                 "as-of date of the queried stock symbol(s)",
	"StockBarSingle.currency":                             "currency of all prices in ISO 4217 format. Default: USD",
	"StockBarSingle.end":                                  "inclusive end of the interval",
	"StockBarSingle.feed":                                 "source feed of the data.",
	"StockBarSingle.limit":                                "maximum number of data points to return in the response page.",
	"StockBarSingle.page_token":                           "pagination token from which to continue",
	"StockBarSingle.sort":                                 "sort data in ascending or descending order",
	"StockBarSingle.start":                                "inclusive start of the interval",
	"StockBarSingle.symbol":                               "symbol to query",
	"StockBarSingle.timeframe":                            "timeframe represented by each bar in aggregation.\nYou can use any of the following values:\n - [1-59]Min or [1-59]T, e.g",
	"StockBars.adjustment":                                "specifies the adjustments for the bars.\n\n - raw: no adjustments\n - split: adjust price and volume for forward and rev...",
	"StockBars.asof":                                      "as-of date of the queried stock symbol(s)",
	"StockBars.currency":                                  "currency of all prices in ISO 4217 format. Default: USD",
	"StockBars.end":                                       "inclusive end of the interval",
	"StockBars.feed":                                      "source feed of the data.",
	"StockBars.limit":                                     "maximum number of data points to return in the response page.",
	"StockBars.page_token":                                "pagination token from which to continue",
	"StockBars.sort":                                      "sort data in ascending or descending order",
	"StockBars.start":                                     "inclusive start of the interval",
	"StockBars.symbols":                                   "A comma-separated list of stock symbols",
	"StockBars.timeframe":                                 "timeframe represented by each bar in aggregation.\nYou can use any of the following values:\n - [1-59]Min or [1-59]T, e.g",
	"StockLatestBarSingle.currency":                       "currency of all prices in ISO 4217 format. Default: USD",
	"StockLatestBarSingle.feed":                           "source feed of the data.",
	"StockLatestBarSingle.symbol":                         "symbol to query",
	"StockLatestBars.currency":                            "currency of all prices in ISO 4217 format. Default: USD",
	"StockLatestBars.feed":                                "source feed of the data.",
	"StockLatestBars.symbols":                             "A comma-separated list of stock symbols",
	"StockLatestQuoteSingle.currency":                     "currency of all prices in ISO 4217 format. Default: USD",
	"StockLatestQuoteSingle.feed":                         "source feed of the data.",
	"StockLatestQuoteSingle.symbol":                       "symbol to query",
	"StockLatestQuotes.currency":                          "currency of all prices in ISO 4217 format. Default: USD",
	"StockLatestQuotes.feed":                              "source feed of the data.",
	"StockLatestQuotes.symbols":                           "A comma-separated list of stock symbols",
	"StockLatestTradeSingle.currency":                     "currency of all prices in ISO 4217 format. Default: USD",
	"StockLatestTradeSingle.feed":                         "source feed of the data.",
	"StockLatestTradeSingle.symbol":                       "symbol to query",
	"StockLatestTrades.currency":                          "currency of all prices in ISO 4217 format. Default: USD",
	"StockLatestTrades.feed":                              "source feed of the data.",
	"StockLatestTrades.symbols":                           "A comma-separated list of stock symbols",
	"StockMetaConditions.tape":                            "one character name of the tape",
	"StockMetaConditions.ticktype":                        "type of ticks",
	"StockQuoteSingle.asof":                               "as-of date of the queried stock symbol(s)",
	"StockQuoteSingle.currency":                           "currency of all prices in ISO 4217 format. Default: USD",
	"StockQuoteSingle.end":                                "inclusive end of the interval",
	"StockQuoteSingle.feed":                               "source feed of the data.",
	"StockQuoteSingle.limit":                              "maximum number of data points to return in the response page.",
	"StockQuoteSingle.page_token":                         "pagination token from which to continue",
	"StockQuoteSingle.sort":                               "sort data in ascending or descending order",
	"StockQuoteSingle.start":                              "inclusive start of the interval",
	"StockQuoteSingle.symbol":                             "symbol to query",
	"StockQuotes.asof":                                    "as-of date of the queried stock symbol(s)",
	"StockQuotes.currency":                                "currency of all prices in ISO 4217 format. Default: USD",
	"StockQuotes.end":                                     "inclusive end of the interval",
	"StockQuotes.feed":                                    "source feed of the data.",
	"StockQuotes.limit":                                   "maximum number of data points to return in the response page.",
	"StockQuotes.page_token":                              "pagination token from which to continue",
	"StockQuotes.sort":                                    "sort data in ascending or descending order",
	"StockQuotes.start":                                   "inclusive start of the interval",
	"StockQuotes.symbols":                                 "A comma-separated list of stock symbols",
	"StockSnapshotSingle.currency":                        "currency of all prices in ISO 4217 format. Default: USD",
	"StockSnapshotSingle.feed":                            "source feed of the data.",
	"StockSnapshotSingle.symbol":                          "symbol to query",
	"StockSnapshots.currency":                             "currency of all prices in ISO 4217 format. Default: USD",
	"StockSnapshots.feed":                                 "source feed of the data.",
	"StockSnapshots.symbols":                              "A comma-separated list of stock symbols",
	"StockTradeSingle.asof":                               "as-of date of the queried stock symbol(s)",
	"StockTradeSingle.currency":                           "currency of all prices in ISO 4217 format. Default: USD",
	"StockTradeSingle.end":                                "inclusive end of the interval",
	"StockTradeSingle.feed":                               "source feed of the data.",
	"StockTradeSingle.limit":                              "maximum number of data points to return in the response page.",
	"StockTradeSingle.page_token":                         "pagination token from which to continue",
	"StockTradeSingle.sort":                               "sort data in ascending or descending order",
	"StockTradeSingle.start":                              "inclusive start of the interval",
	"StockTradeSingle.symbol":                             "symbol to query",
	"StockTrades.asof":                                    "as-of date of the queried stock symbol(s)",
	"StockTrades.currency":                                "currency of all prices in ISO 4217 format. Default: USD",
	"StockTrades.end":                                     "inclusive end of the interval",
	"StockTrades.feed":                                    "source feed of the data.",
	"StockTrades.limit":                                   "maximum number of data points to return in the response page.",
	"StockTrades.page_token":                              "pagination token from which to continue",
	"StockTrades.sort":                                    "sort data in ascending or descending order",
	"StockTrades.start":                                   "inclusive start of the interval",
	"StockTrades.symbols":                                 "A comma-separated list of stock symbols",
	"UsCorporates.bond_status":                            "bond status",
	"UsCorporates.cusips":                                 "A comma-separated list of CUSIPs with a limit of 1000",
	"UsCorporates.isins":                                  "A comma-separated list of ISINs with a limit of 1000",
	"UsCorporates.tickers":                                "A comma-separated list of tickers with a limit of 1000",
	"UsTreasuries.bond_status":                            "bond status",
	"UsTreasuries.cusips":                                 "A comma-separated list of CUSIPs with a limit of 1000",
	"UsTreasuries.isins":                                  "A comma-separated list of ISINs with a limit of 1000",
	"UsTreasuries.subtype":                                "subtype",
	"addAssetToWatchlist.symbol":                          "the symbol name to add to the watchlist",
	"addAssetToWatchlist.watchlist_id":                    "watchlist id",
	"addAssetToWatchlistByName.name":                      "name of the watchlist",
	"addAssetToWatchlistByName.symbol":                    "the symbol name to add to the watchlist",
	"createCryptoPerpTransferForAccount.address":          "destination wallet address",
	"createCryptoPerpTransferForAccount.amount":           "amount, denoted in the specified asset, to be withdrawn from the user’s wallet",
	"createCryptoPerpTransferForAccount.asset":            "asset",
	"createCryptoTransferForAccount.address":              "destination wallet address",
	"createCryptoTransferForAccount.amount":               "amount, denoted in the specified asset, to be withdrawn from the user’s wallet",
	"createCryptoTransferForAccount.asset":                "asset",
	"createWhitelistedAddress.address":                    "address to be whitelisted",
	"createWhitelistedAddress.asset":                      "symbol of underlying asset for the whitelisted address",
	"createWhitelistedPerpAddress.address":                "address to be whitelisted",
	"createWhitelistedPerpAddress.asset":                  "symbol of underlying asset for the whitelisted address",
	"deleteAllOpenPositions.cancel_orders":                "if true is specified, cancel all open orders before liquidating all positions",
	"deleteOpenPosition.percentage":                       "percentage of position to liquidate",
	"deleteOpenPosition.qty":                              "the number of shares to liquidate. Can accept up to 9 decimal points. Cannot work with percentage",
	"deleteOpenPosition.symbol_or_asset_id":               "symbol or assetId",
	"deleteOrderByOrderID.order_id":                       "order id",
	"deleteWatchlistById.watchlist_id":                    "watchlist id",
	"deleteWatchlistByName.name":                          "name of the watchlist",
	"deleteWhitelistedAddress.whitelisted_address_id":     "whitelisted address to delete",
	"deleteWhitelistedPerpAddress.whitelisted_address_id": "whitelisted address to delete",
	"get-option-contract-symbol_or_id.symbol_or_id":       "symbol or contract ID",
	"get-options-contracts.expiration_date":               "filter contracts by the exact expiration date (format: YYYY-MM-DD)",
	"get-options-contracts.expiration_date_gte":           "filter contracts with expiration date greater than or equal to the specified date",
	"get-options-contracts.expiration_date_lte":           "filter contracts with expiration date less than or equal to the specified date",
	"get-options-contracts.limit":                         "number of contracts to limit per page (default=100, max=10000)",
	"get-options-contracts.page_token":                    "used for pagination, this token retrieves the next page of results",
	"get-options-contracts.ppind":                         "ppind(Penny Program Indicator) field indicates whether an option contract is eligible for penny price increments,",
	"get-options-contracts.root_symbol":                   "filter contracts by the root symbol",
	"get-options-contracts.show_deliverables":             "include deliverables array in the response",
	"get-options-contracts.status":                        "filter contracts by status (active/inactive). By default only active contracts are returned",
	"get-options-contracts.strike_price_gte":              "filter contracts with strike price greater than or equal to the specified value",
	"get-options-contracts.strike_price_lte":              "filter contracts with strike price less than or equal to the specified value",
	"get-options-contracts.style":                         "filter contracts by the style (american/european)",
	"get-options-contracts.type":                          "filter contracts by the type (call/put)",
	"get-options-contracts.underlying_symbols":            "filter contracts by one or more underlying symbols",
	"get-v2-assets-symbol_or_asset_id.symbol_or_asset_id": "symbol or assetId. CUSIP is also accepted for US equities",
	"get-v2-assets.asset_class":                           "defaults to us_equity",
	"get-v2-assets.attributes":                            "comma separated values to query for more than one attribute",
	"get-v2-assets.exchange":                              "optional AMEX, ARCA, BATS, NYSE, NASDAQ, NYSEARCA or OTC",
	"get-v2-assets.status":                                "e.g. “active”. By default, all statuses are included",
	"get-v2-corporate_actions-announcements-id.id":        "corporate announcement’s id",
	"get-v2-corporate_actions-announcements.ca_types":     "A comma-delimited list of Dividend, Merger, Spinoff, or Split",
	"get-v2-corporate_actions-announcements.cusip":        "CUSIP of the company initiating the announcement",
	"get-v2-corporate_actions-announcements.date_type":    "declaration_date, ex_date, record_date, or payable_date",
	"get-v2-corporate_actions-announcements.since":        "start (inclusive) of the date range when searching corporate action announcements",
	"get-v2-corporate_actions-announcements.symbol":       "symbol of the company initiating the announcement",
	"get-v2-corporate_actions-announcements.until":        "end (inclusive) of the date range when searching corporate action announcements",
	"getAccountActivities.activity_types":                 "A comma-separated list of activity types used to filter the results",
	"getAccountActivities.after":                          "get activities created after this date. Both formats YYYY-MM-DD and YYYY-MM-DDTHH:MM:SSZ are supported",
	"getAccountActivities.category":                       "activity category. Cannot be used with \"activity_types\" parameter",
	"getAccountActivities.date":                           "filter activities by the activity date. Both formats YYYY-MM-DD and YYYY-MM-DDTHH:MM:SSZ are supported",
	"getAccountActivities.direction":                      "chronological order of response based on the activity datetime",
	"getAccountActivities.page_size":                      "maximum number of entries to return in the response",
	"getAccountActivities.page_token":                     "token used for pagination. Provide the ID of the last activity from the last page to retrieve the next set of results",
	"getAccountActivities.until":                          "get activities created before this date. Both formats YYYY-MM-DD and YYYY-MM-DDTHH:MM:SSZ are supported",
	"getAccountActivitiesByActivityType.activity_type":    "activity type you want to view entries for. A list of valid activity types can be found at the bottom of this page",
	"getAccountActivitiesByActivityType.after":            "get activities created after this date. Both formats YYYY-MM-DD and YYYY-MM-DDTHH:MM:SSZ are supported",
	"getAccountActivitiesByActivityType.date":             "filter activities by the activity date. Both formats YYYY-MM-DD and YYYY-MM-DDTHH:MM:SSZ are supported",
	"getAccountActivitiesByActivityType.direction":        "chronological order of response based on the activity datetime",
	"getAccountActivitiesByActivityType.page_size":        "maximum number of entries to return in the response",
	"getAccountActivitiesByActivityType.page_token":       "token used for pagination. Provide the ID of the last activity from the last page to retrieve the next set of results",
	"getAccountActivitiesByActivityType.until":            "get activities created before this date. Both formats YYYY-MM-DD and YYYY-MM-DDTHH:MM:SSZ are supported",
	"getAccountPortfolioHistory.cashflow_types":           "cashflow activities to include in the report. One of 'ALL', 'NONE', or a comma-separated list of activity types",
	"getAccountPortfolioHistory.end":                      "timestamp the data is returned up to in RFC3339 format (including timezone specification)",
	"getAccountPortfolioHistory.extended_hours":           "**deprecated**: Users are strongly advised to **rely on the intraday_reporting query parameter** for better control\no...",
	"getAccountPortfolioHistory.intraday_reporting":       "for intraday resolutions (<1D) this specfies which timestamps to return data points for:\n\nAllowed values are:\n- **mar...",
	"getAccountPortfolioHistory.period":                   "duration of the data in number + unit format, such as 1D, where unit can be D for day, W for week, M for month and A ...",
	"getAccountPortfolioHistory.pnl_reset":                "pnl_reset defines how we are calculating the baseline values for Profit And Loss (pnl) for queries with timeframe les...",
	"getAccountPortfolioHistory.start":                    "timestamp the data is returned starting from in RFC3339 format (including timezone specification)",
	"getAccountPortfolioHistory.timeframe":                "resolution of time window",
	"getAllOrders.after":                                  "response will include only ones submitted after this timestamp (exclusive.)",
	"getAllOrders.after_order_id":                         "return orders submitted after the order with this ID (exclusive).\nMutually exclusive with before_order_id",
	"getAllOrders.asset_class":                            "A comma seperated list of asset classes, the response will include only orders in the specified asset classes",
	"getAllOrders.before_order_id":                        "return orders submitted before the order with this ID (exclusive).\nMutually exclusive with after_order_id",
	"getAllOrders.direction":                              "chronological order of response based on the submission time. asc or desc. Defaults to desc",
	"getAllOrders.limit":                                  "maximum number of orders in response. Defaults to 50 and max is 500",
	"getAllOrders.nested":                                 "if true, the result will roll up multi-leg orders under the legs field of primary order",
	"getAllOrders.side":                                   "filters down to orders that have a matching side field set",
	"getAllOrders.status":                                 "order status to be queried. open, closed or all. Defaults to open",
	"getAllOrders.symbols":                                "A comma-separated list of symbols to filter by (ex",
	"getAllOrders.until":                                  "response will include only ones submitted until this timestamp (exclusive.)",
	"getCryptoFundingTransfer.transfer_id":                "crypto transfer to retrieve",
	"getCryptoPerpAccountLeverage.symbol":                 "symbol of underlying asset",
	"getCryptoPerpFundingTransfer.transfer_id":            "crypto transfer to retrieve",
	"getCryptoPerpTransferEstimate.amount":                "amount, denoted in the specified asset, of the proposed transaction",
	"getCryptoPerpTransferEstimate.asset":                 "asset for the proposed transaction",
	"getCryptoPerpTransferEstimate.from_address":          "originating address of the proposed transaction",
	"getCryptoPerpTransferEstimate.to_address":            "destination address of the proposed transaction",
	"getCryptoTransferEstimate.amount":                    "amount, denoted in the specified asset, of the proposed transaction",
	"getCryptoTransferEstimate.asset":                     "asset for the proposed transaction",
	"getCryptoTransferEstimate.from_address":              "originating address of the proposed transaction",
	"getCryptoTransferEstimate.to_address":                "destination address of the proposed transaction",
	"getOpenPosition.symbol_or_asset_id":                  "symbol or assetId",
	"getOrderByClientOrderId.client_order_id":             "client-assigned order ID",
	"getOrderByOrderID.nested":                            "if true, the result will roll up multi-leg orders under the legs field of primary order",
	"getOrderByOrderID.order_id":                          "order id",
	"getWatchlistById.watchlist_id":                       "watchlist id",
	"getWatchlistByName.name":                             "name of the watchlist",
	"listCryptoFundingWallets.asset":                      "asset",
	"listCryptoFundingWallets.network":                    "optional network identifier",
	"listCryptoPerpFundingWallets.asset":                  "asset",
	"optionBars.end":                                      "inclusive end of the interval",
	"optionBars.limit":                                    "maximum number of data points to return in the response page.",
	"optionBars.page_token":                               "pagination token from which to continue",
	"optionBars.sort":                                     "sort data in ascending or descending order",
	"optionBars.start":                                    "inclusive start of the interval",
	"optionBars.symbols":                                  "A comma-separated list of contract symbols with a limit of 100",
	"optionBars.timeframe":                                "timeframe represented by each bar in aggregation.\nYou can use any of the following values:\n - [1-59]Min or [1-59]T, e.g",
	"optionDoNotExercise.symbol_or_contract_id":           "option contract symbol or ID",
	"optionExercise.symbol_or_contract_id":                "option contract symbol or ID",
	"patchAccountConfig.disable_overnight_trading":        "if true, overnight trading is disabled",
	"patchAccountConfig.dtbp_check":                       "both, entry, or exit. Controls Day Trading Margin Call (DTMC) checks",
	"patchAccountConfig.fractional_trading":               "if true, account is able to participate in fractional trading",
	"patchAccountConfig.max_margin_multiplier":            "can be \"1\", \"2\", or \"4\"",
	"patchAccountConfig.max_options_trading_level":        "desired maximum options trading level. 0=disabled, 1=Covered Call/Cash-Secured Put, 2=Long Call/Put, 3=Spreads/Straddles",
	"patchAccountConfig.no_shorting":                      "if true, account becomes long-only mode",
	"patchAccountConfig.pdt_check":                        "both, entry, or exit",
	"patchAccountConfig.ptp_no_exception_entry":           "if set to true then Alpaca will accept orders for PTP symbols with no exception. Default is false",
	"patchAccountConfig.suspend_trade":                    "if true, new orders are blocked",
	"patchAccountConfig.trade_confirm_email":              "all or none. If none, emails for order fills are not sent",
	"patchOrderByOrderId.advanced_instructions":           "advanced instructions for Elite Smart Router: https://docs.alpaca.markets/docs/alpaca-elite-smart-router",
	"patchOrderByOrderId.client_order_id":                 "A unique identifier for the new order. Automatically generated if not sent. (<= 128 characters)",
	"patchOrderByOrderId.limit_price":                     "required if original order's type field was limit or stop_limit.",
	"patchOrderByOrderId.order_id":                        "order id",
	"patchOrderByOrderId.qty":                             "number of shares to trade.",
	"patchOrderByOrderId.stop_price":                      "required if original order type is limit or stop_limit",
	"patchOrderByOrderId.time_in_force":                   "time-In-Force values supported by Alpaca vary based on the order's security type",
	"patchOrderByOrderId.trail":                           "the new value of the trail_price or trail_percent value (works only for type=“trailing_stop”)",
	"postOrder.advanced_instructions":                     "advanced instructions for Elite Smart Router: https://docs.alpaca.markets/docs/alpaca-elite-smart-router",
	"postOrder.client_order_id":                           "A unique identifier for the order. Automatically generated if not sent. (<= 128 characters)",
	"postOrder.extended_hours":                            "(default) false",
	"postOrder.legs":                                      "list of order legs (<= 4)",
	"postOrder.limit_price":                               "required if type is limit or stop_limit.",
	"postOrder.notional":                                  "dollar amount to trade. Cannot work with qty. Can only work for market order types and day for time in force",
	"postOrder.order_class":                               "order classes supported by Alpaca vary based on the order's security type",
	"postOrder.position_intent":                           "represents the desired position strategy",
	"postOrder.qty":                                       "number of shares to trade",
	"postOrder.side":                                      "represents which side this order was on:\n- buy\n- sell\nRequired for all order classes except for mleg",
	"postOrder.stop_loss":                                 "takes in string/number values for stop_price and limit_price",
	"postOrder.stop_price":                                "required if type is stop or stop_limit",
	"postOrder.symbol":                                    "symbol, asset ID, or currency pair to identify the asset to trade, required for all order classes except for mleg",
	"postOrder.take_profit":                               "takes in a string/number value for limit_price",
	"postOrder.time_in_force":                             "time-In-Force values supported by Alpaca vary based on the order's security type",
	"postOrder.trail_percent":                             "this or trail_price is required if type is trailing_stop",
	"postOrder.trail_price":                               "this or trail_percent is required if type is trailing_stop",
	"postOrder.type":                                      "order types supported by Alpaca vary based on the order's security type",
	"postWatchlist.name":                                  "name",
	"postWatchlist.symbols":                               "symbols",
	"removeAssetFromWatchlist.symbol":                     "symbol name to remove from the watchlist content",
	"removeAssetFromWatchlist.watchlist_id":               "watchlist ID",
	"setCryptoPerpAccountLeverage.leverage":               "leverage for the underlying asset",
	"setCryptoPerpAccountLeverage.symbol":                 "symbol of underlying asset",
	"updateWatchlistById.name":                            "name",
	"updateWatchlistById.symbols":                         "symbols",
	"updateWatchlistById.watchlist_id":                    "watchlist id",
	"updateWatchlistByName.name":                          "name",
	"updateWatchlistByName.symbols":                       "symbols",
}
