// Code generated by cmd/generate; DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/alpacahq/cli/internal/api"
	"github.com/alpacahq/cli/internal/cmdutil"
	"github.com/spf13/cobra"
)

var accountCmd = &cobra.Command{
	Use:   "account",
	Short: "Manage your trading account",
}

var accountConfigCmd = &cobra.Command{
	Use:   "config",
	Short: "Manage account configuration",
}

var activityCmd = &cobra.Command{
	Use:   "activity",
	Short: "Account activities (fills, dividends, transfers, etc.)",
}

var assetCmd = &cobra.Command{
	Use:   "asset",
	Short: "Browse assets",
}

var calendarCmd = &cobra.Command{
	Use:   "calendar",
	Short: "Market calendar",
}

var clockCmd = &cobra.Command{
	Use:   "clock",
	Short: "Market clock",
}

var corporateActionCmd = &cobra.Command{
	Use:     "corporate-action",
	Short:   "Corporate actions announcements",
	Aliases: []string{"ca"},
}

var cryptoPerpCmd = &cobra.Command{
	Use:   "crypto-perp",
	Short: "Crypto perpetuals (futures)",
}

var cryptoPerpDataCmd = &cobra.Command{
	Use:   "data",
	Short: "Crypto perpetuals market data",
}

var cryptoPerpTransferCmd = &cobra.Command{
	Use:   "transfer",
	Short: "Manage crypto perpetuals transfers",
}

var cryptoPerpWalletCmd = &cobra.Command{
	Use:   "wallet",
	Short: "Crypto perpetuals funding wallets and transfers",
}

var cryptoPerpWhitelistCmd = &cobra.Command{
	Use:   "whitelist",
	Short: "Manage whitelisted perpetuals crypto addresses",
}

var dataCmd = &cobra.Command{
	Use:   "data",
	Short: "Access market data",
}

var dataCryptoCmd = &cobra.Command{
	Use:   "crypto",
	Short: "Crypto market data",
}

var dataForexCmd = &cobra.Command{
	Use:   "forex",
	Short: "Foreign exchange rate data",
}

var dataLatestCmd = &cobra.Command{
	Use:   "latest",
	Short: "Get latest market data",
}

var dataMetaCmd = &cobra.Command{
	Use:   "meta",
	Short: "Stock exchange and condition reference data",
}

var dataOptionCmd = &cobra.Command{
	Use:   "option",
	Short: "Options market data",
}

var optionCmd = &cobra.Command{
	Use:   "option",
	Short: "Options trading",
}

var orderCmd = &cobra.Command{
	Use:   "order",
	Short: "Manage orders",
}

var positionCmd = &cobra.Command{
	Use:   "position",
	Short: "Manage positions",
}

var screenerCmd = &cobra.Command{
	Use:   "screener",
	Short: "Stock and crypto screener and market movers",
}

var walletCmd = &cobra.Command{
	Use:   "wallet",
	Short: "Crypto funding wallets and transfers",
}

var walletTransferCmd = &cobra.Command{
	Use:   "transfer",
	Short: "Manage crypto transfers",
}

var walletWhitelistCmd = &cobra.Command{
	Use:   "whitelist",
	Short: "Manage whitelisted crypto addresses",
}

var watchlistCmd = &cobra.Command{
	Use:   "watchlist",
	Short: "Manage watchlists",
}

var addAssetToWatchlistCmd = fetchCmd("add", api.AddAssetToWatchlistOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.AddAssetToWatchlist(cmdutil.Str(cmd, "watchlist-id"), &api.AddAssetToWatchlistRequest{
		Symbol: cmdutil.Str(cmd, "symbol"),
	})
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist add --watchlist-id <id> --symbol AAPL`
})

var addAssetToWatchlistByNameCmd = fetchCmd("add-by-name", api.AddAssetToWatchlistByNameOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.AddAssetToWatchlistByName(addAssetToWatchlistByNameParamsFromFlags(cmd), &api.AddAssetToWatchlistByNameRequest{
		Symbol: cmdutil.Str(cmd, "symbol"),
	})
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist add-by-name --name "Tech Stocks" --symbol NVDA`
})

var calendarMarketCmd = fetchCmd("market", api.CalendarOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.Calendar(cmdutil.Str(cmd, "market"), calendarParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca calendar market --market XNYS --start 2025-01-01`
})

var clockMarketsCmd = fetchCmd("markets", api.ClockOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.Clock(clockParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca clock markets --markets XNYS,XNAS`
})

var corporateActionsCmd = fetchCmd("corporate-actions", api.CorporateActionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CorporateActions(corporateActionsParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data corporate-actions --symbols AAPL --types forward_split --start 2025-01-01`
})

var createCryptoPerpTransferForAccountCmd = fetchCmd("create", api.CreateCryptoPerpTransferForAccountOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.CreateCryptoPerpTransferForAccount(&api.CreateCryptoTransferRequest{
		Address: cmdutil.Str(cmd, "address"),
		Amount:  cmdutil.Str(cmd, "amount"),
		Asset:   cmdutil.Str(cmd, "asset"),
	})
}, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp wallet transfer create --amount 0.5 --address 0xabc... --asset BTC`
})

var createCryptoTransferForAccountCmd = fetchCmd("create", api.CreateCryptoTransferForAccountOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.CreateCryptoTransferForAccount(&api.CreateCryptoTransferRequest{
		Address: cmdutil.Str(cmd, "address"),
		Amount:  cmdutil.Str(cmd, "amount"),
		Asset:   cmdutil.Str(cmd, "asset"),
	})
}, func(c *cobra.Command) {
	c.Example = `  alpaca wallet transfer create --amount 0.5 --address 0xabc... --asset BTC`
})

var createWhitelistedAddressCmd = fetchCmd("add", api.CreateWhitelistedAddressOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.CreateWhitelistedAddress(&api.CreateWhitelistedAddressRequest{
		Address: cmdutil.Str(cmd, "address"),
		Asset:   cmdutil.Str(cmd, "asset"),
	})
}, func(c *cobra.Command) {
	c.Example = `  alpaca wallet whitelist add --address 0xabc... --asset ETH`
})

var createWhitelistedPerpAddressCmd = fetchCmd("add", api.CreateWhitelistedPerpAddressOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.CreateWhitelistedPerpAddress(&api.CreateWhitelistedPerpAddressRequest{
		Address: cmdutil.Str(cmd, "address"),
		Asset:   cmdutil.Str(cmd, "asset"),
	})
}, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp wallet whitelist add --address 0xabc... --asset ETH`
})

var cryptoBarsCmd = fetchCmd("bars", api.CryptoBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoBars(cmdutil.Str(cmd, "loc"), cryptoBarsParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca data crypto bars --symbols BTC/USD --start 2025-01-01 --timeframe 1Day`
})

var cryptoLatestBarsCmd = fetchCmd("latest-bars", api.CryptoLatestBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoLatestBars(cmdutil.Str(cmd, "loc"), cryptoLatestBarsParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca data crypto latest-bars --symbols BTC/USD`
})

var cryptoLatestOrderbooksCmd = fetchCmd("crypto-orderbook", api.CryptoLatestOrderbooksOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoLatestOrderbooks(cmdutil.Str(cmd, "loc"), cryptoLatestOrderbooksParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca data crypto-orderbook --symbols BTC/USD,ETH/USD`
})

var cryptoLatestQuotesCmd = fetchCmd("latest-quotes", api.CryptoLatestQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoLatestQuotes(cmdutil.Str(cmd, "loc"), cryptoLatestQuotesParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca data crypto latest-quotes --symbols BTC/USD`
})

var cryptoLatestTradesCmd = fetchCmd("latest-trades", api.CryptoLatestTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoLatestTrades(cmdutil.Str(cmd, "loc"), cryptoLatestTradesParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca data crypto latest-trades --symbols BTC/USD`
})

var cryptoPerpLatestBarsCmd = fetchCmd("latest-bars", api.CryptoPerpLatestBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoPerpLatestBars(cmdutil.Str(cmd, "loc"), cryptoPerpLatestBarsParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp data latest-bars --symbols BTC/USD`
})

var cryptoPerpLatestFuturesPricingCmd = fetchCmd("latest-futures-pricing", api.CryptoPerpLatestFuturesPricingOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoPerpLatestFuturesPricing(cmdutil.Str(cmd, "loc"), cryptoPerpLatestFuturesPricingParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp data latest-futures-pricing --symbols BTC/USD`
})

var cryptoPerpLatestOrderbooksCmd = fetchCmd("latest-orderbooks", api.CryptoPerpLatestOrderbooksOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoPerpLatestOrderbooks(cmdutil.Str(cmd, "loc"), cryptoPerpLatestOrderbooksParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp data latest-orderbooks --symbols BTC/USD`
})

var cryptoPerpLatestQuotesCmd = fetchCmd("latest-quotes", api.CryptoPerpLatestQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoPerpLatestQuotes(cmdutil.Str(cmd, "loc"), cryptoPerpLatestQuotesParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp data latest-quotes --symbols BTC/USD`
})

var cryptoPerpLatestTradesCmd = fetchCmd("latest-trades", api.CryptoPerpLatestTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoPerpLatestTrades(cmdutil.Str(cmd, "loc"), cryptoPerpLatestTradesParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp data latest-trades --symbols BTC/USD`
})

var cryptoQuotesCmd = fetchCmd("quotes", api.CryptoQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoQuotes(cmdutil.Str(cmd, "loc"), cryptoQuotesParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca data crypto quotes --symbols BTC/USD --start 2025-01-01`
})

var cryptoSnapshotsCmd = fetchCmd("snapshots", api.CryptoSnapshotsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoSnapshots(cmdutil.Str(cmd, "loc"), cryptoSnapshotsParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca data crypto snapshots --symbols BTC/USD`
})

var cryptoTradesCmd = fetchCmd("trades", api.CryptoTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoTrades(cmdutil.Str(cmd, "loc"), cryptoTradesParamsFromFlags(cmd))
}, jsonOnly, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"loc": "us"}}), func(c *cobra.Command) {
	c.Example = `  alpaca data crypto trades --symbols BTC/USD --start 2025-01-01`
})

var deleteAllOpenPositionsCmd = fetchCmd("close-all", api.DeleteAllOpenPositionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.DeleteAllOpenPositions(deleteAllOpenPositionsParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca position close-all`
})

var deleteAllOrdersCmd = fetchCmd("cancel-all", api.DeleteAllOrdersOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.DeleteAllOrders()
}, func(c *cobra.Command) {
	c.Example = `  alpaca order cancel-all`
})

var deleteOpenPositionCmd = fetchCmd("close", api.DeleteOpenPositionOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.DeleteOpenPosition(normalizePathParam(cmdutil.Str(cmd, "symbol-or-asset-id")), deleteOpenPositionParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca position close --symbol-or-asset-id AAPL
  alpaca position close --symbol-or-asset-id AAPL --qty 5
  alpaca position close --symbol-or-asset-id AAPL --percentage 50`
})

var deleteOrderByOrderIDCmd = fetchCmd("cancel", api.DeleteOrderByOrderIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.DeleteOrderByOrderID(cmdutil.Str(cmd, "order-id")))
}, func(c *cobra.Command) {
	c.Example = `  alpaca order cancel --order-id <id>`
})

var deleteWatchlistByIDCmd = fetchCmd("delete", api.DeleteWatchlistByIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.DeleteWatchlistByID(cmdutil.Str(cmd, "watchlist-id")))
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist delete --watchlist-id <id>`
})

var deleteWatchlistByNameCmd = fetchCmd("delete-by-name", api.DeleteWatchlistByNameOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.DeleteWatchlistByName(deleteWatchlistByNameParamsFromFlags(cmd)))
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist delete-by-name --name "Tech Stocks"`
})

var deleteWhitelistedAddressCmd = fetchCmd("delete", api.DeleteWhitelistedAddressOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.DeleteWhitelistedAddress(cmdutil.Str(cmd, "whitelisted-address-id")))
}, func(c *cobra.Command) {
	c.Example = `  alpaca wallet whitelist delete --whitelisted-address-id <id>`
})

var deleteWhitelistedPerpAddressCmd = fetchCmd("delete", api.DeleteWhitelistedPerpAddressOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.DeleteWhitelistedPerpAddress(cmdutil.Str(cmd, "whitelisted-address-id")))
}, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp wallet whitelist delete --whitelisted-address-id <id>`
})

var fixedIncomeLatestPricesCmd = fetchCmd("fixed-income", api.FixedIncomeLatestPricesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.FixedIncomeLatestPrices(fixedIncomeLatestPricesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data fixed-income --isins 912797KR1,912797LB5`
})

var getAccountCmd = fetchCmd("get", api.GetAccountOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAccount()
}, func(c *cobra.Command) {
	c.Example = `  alpaca account get`
})

var getAccountActivitiesCmd = fetchCmd("list", api.GetAccountActivitiesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetAccountActivities(getAccountActivitiesParamsFromFlags(cmd)))
}, func(c *cobra.Command) {
	c.Example = `  alpaca account activity list
  alpaca account activity list --activity-types FILL,TRANS --page-size 20
  alpaca account activity list --direction desc`
})

var getAccountActivitiesByActivityTypeCmd = fetchCmd("list-by-type", api.GetAccountActivitiesByActivityTypeOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetAccountActivitiesByActivityType(cmdutil.Str(cmd, "activity-type"), getAccountActivitiesByActivityTypeParamsFromFlags(cmd)))
}, func(c *cobra.Command) {
	c.Example = `  alpaca account activity list-by-type --activity-type FILL --page-size 20
  alpaca account activity list-by-type --activity-type DIV --after 2025-01-01`
})

var getAccountConfigCmd = fetchCmd("get", api.GetAccountConfigOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAccountConfig()
}, func(c *cobra.Command) {
	c.Example = `  alpaca account config get`
})

var getAccountPortfolioHistoryCmd = fetchCmd("portfolio", api.GetAccountPortfolioHistoryOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAccountPortfolioHistory(getAccountPortfolioHistoryParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Long = "Returns portfolio equity and P&L history. Output is always JSON due to complex time-series structure."
	c.Example = `  alpaca account portfolio
  alpaca account portfolio --period 1M --timeframe 1D`
})

var getAllOpenPositionsCmd = fetchCmd("list", api.GetAllOpenPositionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAllOpenPositions()
}, func(c *cobra.Command) {
	c.Example = `  alpaca position list
  alpaca position list --csv`
})

var getAllOrdersCmd = fetchCmd("list", api.GetAllOrdersOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAllOrders(getAllOrdersParamsFromFlags(cmd))
}, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"status": "open"}}), func(c *cobra.Command) {
	c.Example = `  alpaca order list
  alpaca order list --status closed --limit 20
  alpaca order list --symbols AAPL,MSFT --after 2025-01-01`
})

var getCryptoFundingTransferCmd = fetchCmd("get", api.GetCryptoFundingTransferOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetCryptoFundingTransfer(cmdutil.Str(cmd, "transfer-id"))
}, func(c *cobra.Command) {
	c.Example = `  alpaca wallet transfer get --transfer-id <id>`
})

var getCryptoPerpAccountLeverageCmd = fetchCmd("leverage", api.GetCryptoPerpAccountLeverageOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetCryptoPerpAccountLeverage(getCryptoPerpAccountLeverageParamsFromFlags(cmd)))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp leverage`
})

var getCryptoPerpAccountVitalsCmd = fetchCmd("vitals", api.GetCryptoPerpAccountVitalsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetCryptoPerpAccountVitals())
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp vitals`
})

var getCryptoPerpFundingTransferCmd = fetchCmd("get", api.GetCryptoPerpFundingTransferOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetCryptoPerpFundingTransfer(cmdutil.Str(cmd, "transfer-id"))
}, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp wallet transfer get --transfer-id <id>`
})

var getCryptoPerpTransferEstimateCmd = fetchCmd("estimate", api.GetCryptoPerpTransferEstimateOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetCryptoPerpTransferEstimate(getCryptoPerpTransferEstimateParamsFromFlags(cmd)))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp wallet transfer estimate --asset BTC --amount 0.5`
})

var getCryptoTransferEstimateCmd = fetchCmd("estimate", api.GetCryptoTransferEstimateOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetCryptoTransferEstimate(getCryptoTransferEstimateParamsFromFlags(cmd)))
}, func(c *cobra.Command) {
	c.Example = `  alpaca wallet transfer estimate --asset BTC --amount 0.5 \
    --from-address 0xabc... --to-address 0xdef...`
})

var getOpenPositionCmd = fetchCmd("get", api.GetOpenPositionOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetOpenPosition(normalizePathParam(cmdutil.Str(cmd, "symbol-or-asset-id")))
}, func(c *cobra.Command) {
	c.Example = `  alpaca position get --symbol-or-asset-id AAPL
  alpaca position get --symbol-or-asset-id BTC/USD`
})

var getOptionContractSymbolOrIDCmd = fetchCmd("get", api.GetOptionContractSymbolOrIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetOptionContractSymbolOrID(cmdutil.Str(cmd, "symbol-or-id"))
}, func(c *cobra.Command) {
	c.Example = `  alpaca option get --symbol-or-id AAPL250620C00200000`
})

var getOptionsContractsCmd = fetchCmd("contracts", api.GetOptionsContractsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetOptionsContracts(getOptionsContractsParamsFromFlags(cmd)))
}, func(c *cobra.Command) {
	c.Long = "List option contracts for an underlying symbol. For market data (greeks, pricing), use `data option chain`."
	c.Example = `  alpaca option contracts --underlying-symbols AAPL
  alpaca option contracts --underlying-symbols AAPL --expiration-date 2025-06-20 --type call
  alpaca option contracts --underlying-symbols SPY --strike-price-gte 400 --strike-price-lte 450`
})

var getOrderByClientOrderIDCmd = fetchCmd("get-by-client-id", api.GetOrderByClientOrderIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetOrderByClientOrderID(getOrderByClientOrderIDParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca order get-by-client-id --client-order-id my-order-123`
})

var getOrderByOrderIDCmd = fetchCmd("get", api.GetOrderByOrderIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetOrderByOrderID(cmdutil.Str(cmd, "order-id"), getOrderByOrderIDParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca order get --order-id 61e69015-8549-4baf-b96f-9c4f3e8d0c35`
})

var getV2AssetsCmd = fetchCmd("list", api.GetV2AssetsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetV2Assets(getV2AssetsParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca asset list
  alpaca asset list --asset-class us_equity --status active
  alpaca asset list --exchange NYSE`
})

var getV2AssetsSymbolOrAssetIDCmd = fetchCmd("get", api.GetV2AssetsSymbolOrAssetIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetV2AssetsSymbolOrAssetID(cmdutil.Str(cmd, "symbol-or-asset-id"))
}, func(c *cobra.Command) {
	c.Example = `  alpaca asset get --symbol-or-asset-id AAPL
  alpaca asset get --symbol-or-asset-id BTC/USD`
})

var getV2CorporateActionsAnnouncementsCmd = fetchCmd("list", api.GetV2CorporateActionsAnnouncementsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetV2CorporateActionsAnnouncements(getV2CorporateActionsAnnouncementsParamsFromFlags(cmd)))
}, func(c *cobra.Command) {
	c.Example = `  alpaca corporate-action list --ca-types reverse_split --since 2025-01-01 --until 2025-12-31
  alpaca corporate-action list --ca-types cash_dividend --symbol AAPL --since 2025-01-01 --until 2025-06-30`
})

var getV2CorporateActionsAnnouncementsIDCmd = fetchCmd("get", api.GetV2CorporateActionsAnnouncementsIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetV2CorporateActionsAnnouncementsID(cmdutil.Str(cmd, "id")))
}, func(c *cobra.Command) {
	c.Example = `  alpaca corporate-action get --id <announcement-id>`
})

var getWatchlistByIDCmd = fetchCmd("get", api.GetWatchlistByIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetWatchlistByID(cmdutil.Str(cmd, "watchlist-id"))
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist get --watchlist-id <id>`
})

var getWatchlistByNameCmd = fetchCmd("get-by-name", api.GetWatchlistByNameOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetWatchlistByName(getWatchlistByNameParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist get-by-name --name "Tech Stocks"`
})

var getWatchlistsCmd = fetchCmd("list", api.GetWatchlistsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetWatchlists()
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist list`
})

var latestRatesCmd = fetchCmd("latest", api.LatestRatesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.LatestRates(latestRatesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data forex latest --currency-pairs EUR/USD,GBP/USD`
})

func init() {
	attachCmd(calendarCmd, api.LegacyCalendarOp, func(cmd *cobra.Command, args []string) (any, error) {
		return voidResponse(tradingClient.LegacyCalendar(legacyCalendarParamsFromFlags(cmd)))
	}, func(c *cobra.Command) {
		c.Example = `  alpaca calendar
  alpaca calendar --start 2025-01-01 --end 2025-12-31`
	})
}

func init() {
	attachCmd(clockCmd, api.LegacyClockOp, func(cmd *cobra.Command, args []string) (any, error) {
		return tradingClient.LegacyClock()
	}, func(c *cobra.Command) {
		c.Example = `  alpaca clock`
	})
}

var listCryptoFundingTransfersCmd = fetchCmd("list", api.ListCryptoFundingTransfersOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListCryptoFundingTransfers()
}, func(c *cobra.Command) {
	c.Example = `  alpaca wallet transfer list`
})

var listCryptoFundingWalletsCmd = fetchCmd("list", api.ListCryptoFundingWalletsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListCryptoFundingWallets(listCryptoFundingWalletsParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca wallet list`
})

var listCryptoPerpFundingTransfersCmd = fetchCmd("list", api.ListCryptoPerpFundingTransfersOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListCryptoPerpFundingTransfers()
}, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp wallet transfer list`
})

var listCryptoPerpFundingWalletsCmd = fetchCmd("list", api.ListCryptoPerpFundingWalletsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListCryptoPerpFundingWallets(listCryptoPerpFundingWalletsParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp wallet list`
})

var listWhitelistedAddressCmd = fetchCmd("list", api.ListWhitelistedAddressOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListWhitelistedAddress()
}, func(c *cobra.Command) {
	c.Example = `  alpaca wallet whitelist list`
})

var listWhitelistedPerpAddressCmd = fetchCmd("list", api.ListWhitelistedPerpAddressOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListWhitelistedPerpAddress()
}, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp wallet whitelist list`
})

var logosCmd = fetchCmd("logo", api.LogosOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.Logos(cmdutil.Str(cmd, "symbol"), logosParamsFromFlags(cmd)))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data logo --symbol AAPL`
})

var mostActivesCmd = fetchCmd("most-actives", api.MostActivesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.MostActives(mostActivesParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca data screener most-actives
  alpaca data screener most-actives --by trades --top 10`
})

var moversCmd = fetchCmd("movers", api.MoversOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.Movers(cmdutil.Str(cmd, "market-type"), moversParamsFromFlags(cmd))
}, flagOpts(&cmdutil.FlagOpts{Defaults: map[string]string{"market_type": "stocks"}}), func(c *cobra.Command) {
	c.Example = `  alpaca data screener movers
  alpaca data screener movers --market-type crypto --top 5`
})

var newsCmd = fetchCmd("news", api.NewsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.News(newsParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca data news
  alpaca data news --symbols AAPL,MSFT --limit 10`
})

var optionBarsCmd = fetchCmd("bars", api.OptionBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionBars(optionBarsParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data option bars --symbols AAPL250620C00200000 --start 2025-01-01
  alpaca data option bars --symbols AAPL250620C00200000,AAPL250620P00200000 --timeframe 1Day`
})

var optionChainCmd = fetchCmd("chain", api.OptionChainOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionChain(cmdutil.Str(cmd, "underlying-symbol"), optionChainParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data option chain --underlying-symbol AAPL
  alpaca data option chain --underlying-symbol SPY --expiration-date 2025-06-20 --type call`
})

var optionDoNotExerciseCmd = fetchCmd("do-not-exercise", api.OptionDoNotExerciseOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.OptionDoNotExercise(cmdutil.Str(cmd, "symbol-or-contract-id")))
}, func(c *cobra.Command) {
	c.Example = `  alpaca option do-not-exercise --symbol-or-contract-id AAPL250620C00200000`
})

var optionExerciseCmd = fetchCmd("exercise", api.OptionExerciseOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.OptionExercise(cmdutil.Str(cmd, "symbol-or-contract-id")))
}, func(c *cobra.Command) {
	c.Example = `  alpaca option exercise --symbol-or-contract-id AAPL250620C00200000`
})

var optionLatestQuotesCmd = fetchCmd("latest-quotes", api.OptionLatestQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionLatestQuotes(optionLatestQuotesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data option latest-quotes --symbols AAPL250620C00200000`
})

var optionLatestTradesCmd = fetchCmd("latest-trades", api.OptionLatestTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionLatestTrades(optionLatestTradesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data option latest-trades --symbols AAPL250620C00200000`
})

var optionMetaConditionsCmd = fetchCmd("conditions", api.OptionMetaConditionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.OptionMetaConditions(cmdutil.Str(cmd, "ticktype")))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data option conditions --ticktype trade`
})

var optionMetaExchangesCmd = fetchCmd("exchanges", api.OptionMetaExchangesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.OptionMetaExchanges())
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data option exchanges`
})

var optionSnapshotsCmd = fetchCmd("snapshot", api.OptionSnapshotsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionSnapshots(optionSnapshotsParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data option snapshot --symbols AAPL250620C00200000
  alpaca data option snapshot --symbols AAPL250620C00200000,AAPL250620P00200000`
})

var optionTradesCmd = fetchCmd("trades", api.OptionTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionTrades(optionTradesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data option trades --symbols AAPL250620C00200000 --start 2025-01-01`
})

var patchAccountConfigCmd = fetchCmd("set", api.PatchAccountConfigOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, changed := accountConfigurationsBodyFromFlags(cmd)
	if !changed {
		return nil, fmt.Errorf("specify at least one flag to change (see '%s --help')", cmd.CommandPath())
	}
	return tradingClient.PatchAccountConfig(body)
}, func(c *cobra.Command) {
	c.Example = `  alpaca account config set --no-shorting true
  alpaca account config set --dtbp-check entry`
})

var patchOrderByOrderIDCmd = fetchCmd("replace", api.PatchOrderByOrderIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, changed := patchOrderRequestBodyFromFlags(cmd)
	if cmdutil.Changed(cmd, "advanced-instructions") {
		if err := json.Unmarshal([]byte(cmdutil.Str(cmd, "advanced-instructions")), &body.AdvancedInstructions); err != nil {
			return nil, fmt.Errorf("--advanced-instructions: %w", err)
		}
		changed = true
	}
	if !changed {
		return nil, fmt.Errorf("specify at least one flag to change (see '%s --help')", cmd.CommandPath())
	}
	return tradingClient.PatchOrderByOrderID(cmdutil.Str(cmd, "order-id"), body)
}, func(c *cobra.Command) {
	c.Example = `  alpaca order replace --order-id <id> --qty 20 --limit-price 190.00`
})

var postWatchlistCmd = fetchCmd("create", api.PostWatchlistOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.UpdateWatchlistRequest{
		Name: cmdutil.Str(cmd, "name"),
	}
	if s := cmdutil.Str(cmd, "symbols"); s != "" {
		body.Symbols = strings.Split(s, ",")
	}
	return tradingClient.PostWatchlist(body)
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist create --name "Tech Stocks" --symbols AAPL,MSFT,GOOG`
})

var ratesCmd = fetchCmd("rates", api.RatesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.Rates(ratesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data forex rates --currency-pairs EUR/USD,GBP/USD --start 2025-01-01
  alpaca data forex rates --currency-pairs USD/JPY --timeframe 1Hour`
})

var removeAssetFromWatchlistCmd = fetchCmd("remove", api.RemoveAssetFromWatchlistOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.RemoveAssetFromWatchlist(cmdutil.Str(cmd, "watchlist-id"), cmdutil.Str(cmd, "symbol"))
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist remove --watchlist-id <id> --symbol AAPL`
})

var setCryptoPerpAccountLeverageCmd = fetchCmd("set-leverage", api.SetCryptoPerpAccountLeverageOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.SetCryptoPerpAccountLeverage(setCryptoPerpAccountLeverageParamsFromFlags(cmd)))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca crypto-perp set-leverage --asset BTC --leverage 5`
})

var stockAuctionSingleCmd = fetchCmd("auction", api.StockAuctionSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockAuctionSingle(cmdutil.Str(cmd, "symbol"), stockAuctionSingleParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data auction --symbol AAPL --start 2025-01-01`
})

var stockAuctionsCmd = fetchCmd("auctions", api.StockAuctionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockAuctions(stockAuctionsParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data auctions --symbols AAPL --start 2025-01-01
  alpaca data auctions --symbols AAPL,MSFT --limit 10`
})

var stockBarSingleCmd = fetchCmd("bars", api.StockBarSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.Bars(cmdutil.Str(cmd, "symbol"), stockBarSingleParamsFromFlags(cmd).Values())
}, func(c *cobra.Command) {
	c.Example = `  alpaca data bars --symbol AAPL --start 2025-01-01 --timeframe 1Day
  alpaca data bars --symbol BTC/USD --start 2025-01-01 --timeframe 1Hour
  alpaca data bars --symbol AAPL --start 2025-01-01 --end 2025-06-01 --limit 100`
})

var stockBarsCmd = fetchCmd("multi-bars", api.StockBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockBars(stockBarsParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data multi-bars --symbols AAPL,MSFT --start 2025-01-01 --timeframe 1Day`
})

var stockLatestBarSingleCmd = fetchCmd("bar", api.StockLatestBarSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.LatestBar(cmdutil.Str(cmd, "symbol"), stockLatestBarSingleParamsFromFlags(cmd).Values())
}, func(c *cobra.Command) {
	c.Example = `  alpaca data latest bar --symbol AAPL
  alpaca data latest bar --symbol BTC/USD`
})

var stockLatestBarsCmd = fetchCmd("bars", api.StockLatestBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockLatestBars(stockLatestBarsParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data latest bars --symbols AAPL,MSFT`
})

var stockLatestQuoteSingleCmd = fetchCmd("quote", api.StockLatestQuoteSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.LatestQuote(cmdutil.Str(cmd, "symbol"), stockLatestQuoteSingleParamsFromFlags(cmd).Values())
}, func(c *cobra.Command) {
	c.Example = `  alpaca data latest quote --symbol AAPL`
})

var stockLatestQuotesCmd = fetchCmd("quotes", api.StockLatestQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockLatestQuotes(stockLatestQuotesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data latest quotes --symbols AAPL,MSFT`
})

var stockLatestTradeSingleCmd = fetchCmd("trade", api.StockLatestTradeSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.LatestTrade(cmdutil.Str(cmd, "symbol"), stockLatestTradeSingleParamsFromFlags(cmd).Values())
}, func(c *cobra.Command) {
	c.Example = `  alpaca data latest trade --symbol AAPL
  alpaca data latest trade --symbol AAPL --feed sip`
})

var stockLatestTradesCmd = fetchCmd("trades", api.StockLatestTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockLatestTrades(stockLatestTradesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data latest trades --symbols AAPL,MSFT`
})

var stockMetaConditionsCmd = fetchCmd("conditions", api.StockMetaConditionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.StockMetaConditions(cmdutil.Str(cmd, "ticktype"), stockMetaConditionsParamsFromFlags(cmd)))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data meta conditions --ticktype trade`
})

var stockMetaExchangesCmd = fetchCmd("exchanges", api.StockMetaExchangesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.StockMetaExchanges())
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data meta exchanges`
})

var stockQuoteSingleCmd = fetchCmd("quotes", api.StockQuoteSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.Quotes(cmdutil.Str(cmd, "symbol"), stockQuoteSingleParamsFromFlags(cmd).Values())
}, func(c *cobra.Command) {
	c.Example = `  alpaca data quotes --symbol AAPL --start 2025-01-01
  alpaca data quotes --symbol AAPL --start 2025-01-01 --end 2025-01-31 --limit 50`
})

var stockQuotesCmd = fetchCmd("multi-quotes", api.StockQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockQuotes(stockQuotesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data multi-quotes --symbols AAPL,MSFT --start 2025-01-01`
})

var stockSnapshotSingleCmd = fetchCmd("snapshot", api.StockSnapshotSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.Snapshot(cmdutil.Str(cmd, "symbol"), stockSnapshotSingleParamsFromFlags(cmd).Values())
}, jsonOnly, func(c *cobra.Command) {
	c.Long = "Returns the latest snapshot for a symbol. Output is always JSON due to complex nested structure."
	c.Example = `  alpaca data snapshot --symbol AAPL
  alpaca data snapshot --symbol BTC/USD --feed sip`
})

var stockSnapshotsCmd = fetchCmd("multi-snapshots", api.StockSnapshotsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.StockSnapshots(stockSnapshotsParamsFromFlags(cmd)))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data multi-snapshots --symbols AAPL,MSFT`
})

var stockTradeSingleCmd = fetchCmd("trades", api.StockTradeSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.Trades(cmdutil.Str(cmd, "symbol"), stockTradeSingleParamsFromFlags(cmd).Values())
}, func(c *cobra.Command) {
	c.Example = `  alpaca data trades --symbol AAPL --start 2025-01-01
  alpaca data trades --symbol AAPL --start 2025-01-01 --limit 100`
})

var stockTradesCmd = fetchCmd("multi-trades", api.StockTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockTrades(stockTradesParamsFromFlags(cmd))
}, jsonOnly, func(c *cobra.Command) {
	c.Example = `  alpaca data multi-trades --symbols AAPL,MSFT --start 2025-01-01`
})

var updateWatchlistByIDCmd = fetchCmd("update", api.UpdateWatchlistByIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, changed := updateWatchlistRequestBodyFromFlags(cmd)
	if !changed {
		return nil, fmt.Errorf("specify at least one flag to change (see '%s --help')", cmd.CommandPath())
	}
	return tradingClient.UpdateWatchlistByID(cmdutil.Str(cmd, "watchlist-id"), body)
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist update --watchlist-id <id> --name "Updated" --symbols AAPL,MSFT`
})

var updateWatchlistByNameCmd = fetchCmd("update-by-name", api.UpdateWatchlistByNameOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.UpdateWatchlistRequest{}
	var changed bool
	if cmdutil.Changed(cmd, "new-name") {
		body.Name = cmdutil.Str(cmd, "new-name")
		changed = true
	}
	if cmdutil.Changed(cmd, "symbols") {
		if s := cmdutil.Str(cmd, "symbols"); s != "" {
			body.Symbols = strings.Split(s, ",")
		}
		changed = true
	}
	if !changed {
		return nil, fmt.Errorf("specify at least one flag to change (see '%s --help')", cmd.CommandPath())
	}
	return tradingClient.UpdateWatchlistByName(updateWatchlistByNameParamsFromFlags(cmd), body)
}, func(c *cobra.Command) {
	c.Flags().String("new-name", "", "The watchlist name.")
}, func(c *cobra.Command) {
	c.Example = `  alpaca watchlist update-by-name --name "Tech Stocks" --new-name "Technology" --symbols AAPL,MSFT`
})

var usCorporatesCmd = fetchCmd("bond", api.UsCorporatesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.UsCorporates(usCorporatesParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca asset bond
  alpaca asset bond --bond-status active`
})

var usTreasuriesCmd = fetchCmd("treasury", api.UsTreasuriesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.UsTreasuries(usTreasuriesParamsFromFlags(cmd))
}, func(c *cobra.Command) {
	c.Example = `  alpaca asset treasury
  alpaca asset treasury --bond-status active`
})

func init() {
	accountCmd.AddCommand(accountConfigCmd)
	accountCmd.AddCommand(activityCmd)
	cryptoPerpCmd.AddCommand(cryptoPerpDataCmd)
	cryptoPerpWalletCmd.AddCommand(cryptoPerpTransferCmd)
	cryptoPerpCmd.AddCommand(cryptoPerpWalletCmd)
	cryptoPerpWalletCmd.AddCommand(cryptoPerpWhitelistCmd)
	dataCmd.AddCommand(dataCryptoCmd)
	dataCmd.AddCommand(dataForexCmd)
	dataCmd.AddCommand(dataLatestCmd)
	dataCmd.AddCommand(dataMetaCmd)
	dataCmd.AddCommand(dataOptionCmd)
	dataCmd.AddCommand(screenerCmd)
	walletCmd.AddCommand(walletTransferCmd)
	walletCmd.AddCommand(walletWhitelistCmd)

	watchlistCmd.AddCommand(addAssetToWatchlistCmd)
	watchlistCmd.AddCommand(addAssetToWatchlistByNameCmd)
	calendarCmd.AddCommand(calendarMarketCmd)
	clockCmd.AddCommand(clockMarketsCmd)
	dataCmd.AddCommand(corporateActionsCmd)
	cryptoPerpTransferCmd.AddCommand(createCryptoPerpTransferForAccountCmd)
	walletTransferCmd.AddCommand(createCryptoTransferForAccountCmd)
	walletWhitelistCmd.AddCommand(createWhitelistedAddressCmd)
	cryptoPerpWhitelistCmd.AddCommand(createWhitelistedPerpAddressCmd)
	dataCryptoCmd.AddCommand(cryptoBarsCmd)
	dataCryptoCmd.AddCommand(cryptoLatestBarsCmd)
	dataCmd.AddCommand(cryptoLatestOrderbooksCmd)
	dataCryptoCmd.AddCommand(cryptoLatestQuotesCmd)
	dataCryptoCmd.AddCommand(cryptoLatestTradesCmd)
	cryptoPerpDataCmd.AddCommand(cryptoPerpLatestBarsCmd)
	cryptoPerpDataCmd.AddCommand(cryptoPerpLatestFuturesPricingCmd)
	cryptoPerpDataCmd.AddCommand(cryptoPerpLatestOrderbooksCmd)
	cryptoPerpDataCmd.AddCommand(cryptoPerpLatestQuotesCmd)
	cryptoPerpDataCmd.AddCommand(cryptoPerpLatestTradesCmd)
	dataCryptoCmd.AddCommand(cryptoQuotesCmd)
	dataCryptoCmd.AddCommand(cryptoSnapshotsCmd)
	dataCryptoCmd.AddCommand(cryptoTradesCmd)
	positionCmd.AddCommand(deleteAllOpenPositionsCmd)
	orderCmd.AddCommand(deleteAllOrdersCmd)
	positionCmd.AddCommand(deleteOpenPositionCmd)
	orderCmd.AddCommand(deleteOrderByOrderIDCmd)
	watchlistCmd.AddCommand(deleteWatchlistByIDCmd)
	watchlistCmd.AddCommand(deleteWatchlistByNameCmd)
	walletWhitelistCmd.AddCommand(deleteWhitelistedAddressCmd)
	cryptoPerpWhitelistCmd.AddCommand(deleteWhitelistedPerpAddressCmd)
	dataCmd.AddCommand(fixedIncomeLatestPricesCmd)
	accountCmd.AddCommand(getAccountCmd)
	activityCmd.AddCommand(getAccountActivitiesCmd)
	activityCmd.AddCommand(getAccountActivitiesByActivityTypeCmd)
	accountConfigCmd.AddCommand(getAccountConfigCmd)
	accountCmd.AddCommand(getAccountPortfolioHistoryCmd)
	positionCmd.AddCommand(getAllOpenPositionsCmd)
	orderCmd.AddCommand(getAllOrdersCmd)
	walletTransferCmd.AddCommand(getCryptoFundingTransferCmd)
	cryptoPerpCmd.AddCommand(getCryptoPerpAccountLeverageCmd)
	cryptoPerpCmd.AddCommand(getCryptoPerpAccountVitalsCmd)
	cryptoPerpTransferCmd.AddCommand(getCryptoPerpFundingTransferCmd)
	cryptoPerpTransferCmd.AddCommand(getCryptoPerpTransferEstimateCmd)
	walletTransferCmd.AddCommand(getCryptoTransferEstimateCmd)
	positionCmd.AddCommand(getOpenPositionCmd)
	optionCmd.AddCommand(getOptionContractSymbolOrIDCmd)
	optionCmd.AddCommand(getOptionsContractsCmd)
	orderCmd.AddCommand(getOrderByClientOrderIDCmd)
	orderCmd.AddCommand(getOrderByOrderIDCmd)
	assetCmd.AddCommand(getV2AssetsCmd)
	assetCmd.AddCommand(getV2AssetsSymbolOrAssetIDCmd)
	corporateActionCmd.AddCommand(getV2CorporateActionsAnnouncementsCmd)
	corporateActionCmd.AddCommand(getV2CorporateActionsAnnouncementsIDCmd)
	watchlistCmd.AddCommand(getWatchlistByIDCmd)
	watchlistCmd.AddCommand(getWatchlistByNameCmd)
	watchlistCmd.AddCommand(getWatchlistsCmd)
	dataForexCmd.AddCommand(latestRatesCmd)
	walletTransferCmd.AddCommand(listCryptoFundingTransfersCmd)
	walletCmd.AddCommand(listCryptoFundingWalletsCmd)
	cryptoPerpTransferCmd.AddCommand(listCryptoPerpFundingTransfersCmd)
	cryptoPerpWalletCmd.AddCommand(listCryptoPerpFundingWalletsCmd)
	walletWhitelistCmd.AddCommand(listWhitelistedAddressCmd)
	cryptoPerpWhitelistCmd.AddCommand(listWhitelistedPerpAddressCmd)
	dataCmd.AddCommand(logosCmd)
	screenerCmd.AddCommand(mostActivesCmd)
	screenerCmd.AddCommand(moversCmd)
	dataCmd.AddCommand(newsCmd)
	dataOptionCmd.AddCommand(optionBarsCmd)
	dataOptionCmd.AddCommand(optionChainCmd)
	optionCmd.AddCommand(optionDoNotExerciseCmd)
	optionCmd.AddCommand(optionExerciseCmd)
	dataOptionCmd.AddCommand(optionLatestQuotesCmd)
	dataOptionCmd.AddCommand(optionLatestTradesCmd)
	dataOptionCmd.AddCommand(optionMetaConditionsCmd)
	dataOptionCmd.AddCommand(optionMetaExchangesCmd)
	dataOptionCmd.AddCommand(optionSnapshotsCmd)
	dataOptionCmd.AddCommand(optionTradesCmd)
	accountConfigCmd.AddCommand(patchAccountConfigCmd)
	orderCmd.AddCommand(patchOrderByOrderIDCmd)
	watchlistCmd.AddCommand(postWatchlistCmd)
	dataForexCmd.AddCommand(ratesCmd)
	watchlistCmd.AddCommand(removeAssetFromWatchlistCmd)
	cryptoPerpCmd.AddCommand(setCryptoPerpAccountLeverageCmd)
	dataCmd.AddCommand(stockAuctionSingleCmd)
	dataCmd.AddCommand(stockAuctionsCmd)
	dataCmd.AddCommand(stockBarSingleCmd)
	dataCmd.AddCommand(stockBarsCmd)
	dataLatestCmd.AddCommand(stockLatestBarSingleCmd)
	dataLatestCmd.AddCommand(stockLatestBarsCmd)
	dataLatestCmd.AddCommand(stockLatestQuoteSingleCmd)
	dataLatestCmd.AddCommand(stockLatestQuotesCmd)
	dataLatestCmd.AddCommand(stockLatestTradeSingleCmd)
	dataLatestCmd.AddCommand(stockLatestTradesCmd)
	dataMetaCmd.AddCommand(stockMetaConditionsCmd)
	dataMetaCmd.AddCommand(stockMetaExchangesCmd)
	dataCmd.AddCommand(stockQuoteSingleCmd)
	dataCmd.AddCommand(stockQuotesCmd)
	dataCmd.AddCommand(stockSnapshotSingleCmd)
	dataCmd.AddCommand(stockSnapshotsCmd)
	dataCmd.AddCommand(stockTradeSingleCmd)
	dataCmd.AddCommand(stockTradesCmd)
	watchlistCmd.AddCommand(updateWatchlistByIDCmd)
	watchlistCmd.AddCommand(updateWatchlistByNameCmd)
	assetCmd.AddCommand(usCorporatesCmd)
	assetCmd.AddCommand(usTreasuriesCmd)
}
