// Code generated by cmd/generate; DO NOT EDIT.

package cmd

import (
	"github.com/alpacahq/cli/internal/api"
	"github.com/alpacahq/cli/internal/cmdutil"
	"github.com/spf13/cobra"
)

func addAssetToWatchlistByNameParamsFromFlags(cmd *cobra.Command) *api.AddAssetToWatchlistByNameParams {
	p := &api.AddAssetToWatchlistByNameParams{}
	flags := cmd.Flags()
	if flags.Changed("name") {
		p.Name = cmdutil.Str(cmd, "name")
	}
	return p
}

func calendarParamsFromFlags(cmd *cobra.Command) *api.CalendarParams {
	p := &api.CalendarParams{}
	flags := cmd.Flags()
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("timezone") {
		p.Timezone = cmdutil.Str(cmd, "timezone")
	}
	return p
}

func clockParamsFromFlags(cmd *cobra.Command) *api.ClockParams {
	p := &api.ClockParams{}
	flags := cmd.Flags()
	if flags.Changed("markets") {
		p.Markets = cmdutil.Str(cmd, "markets")
	}
	if flags.Changed("time") {
		p.Time = cmdutil.Str(cmd, "time")
	}
	return p
}

func corporateActionsParamsFromFlags(cmd *cobra.Command) *api.CorporateActionsParams {
	p := &api.CorporateActionsParams{}
	flags := cmd.Flags()
	if flags.Changed("cusips") {
		p.Cusips = cmdutil.Str(cmd, "cusips")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("ids") {
		p.Ids = cmdutil.Str(cmd, "ids")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Changed("types") {
		p.Types = cmdutil.Str(cmd, "types")
	}
	return p
}

func cryptoBarsParamsFromFlags(cmd *cobra.Command) *api.CryptoBarsParams {
	p := &api.CryptoBarsParams{}
	flags := cmd.Flags()
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Changed("timeframe") {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func cryptoLatestBarsParamsFromFlags(cmd *cobra.Command) *api.CryptoLatestBarsParams {
	p := &api.CryptoLatestBarsParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoLatestOrderbooksParamsFromFlags(cmd *cobra.Command) *api.CryptoLatestOrderbooksParams {
	p := &api.CryptoLatestOrderbooksParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoLatestQuotesParamsFromFlags(cmd *cobra.Command) *api.CryptoLatestQuotesParams {
	p := &api.CryptoLatestQuotesParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoLatestTradesParamsFromFlags(cmd *cobra.Command) *api.CryptoLatestTradesParams {
	p := &api.CryptoLatestTradesParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestBarsParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestBarsParams {
	p := &api.CryptoPerpLatestBarsParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestFuturesPricingParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestFuturesPricingParams {
	p := &api.CryptoPerpLatestFuturesPricingParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestOrderbooksParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestOrderbooksParams {
	p := &api.CryptoPerpLatestOrderbooksParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestQuotesParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestQuotesParams {
	p := &api.CryptoPerpLatestQuotesParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestTradesParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestTradesParams {
	p := &api.CryptoPerpLatestTradesParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoQuotesParamsFromFlags(cmd *cobra.Command) *api.CryptoQuotesParams {
	p := &api.CryptoQuotesParams{}
	flags := cmd.Flags()
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoSnapshotsParamsFromFlags(cmd *cobra.Command) *api.CryptoSnapshotsParams {
	p := &api.CryptoSnapshotsParams{}
	flags := cmd.Flags()
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoTradesParamsFromFlags(cmd *cobra.Command) *api.CryptoTradesParams {
	p := &api.CryptoTradesParams{}
	flags := cmd.Flags()
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func deleteAllOpenPositionsParamsFromFlags(cmd *cobra.Command) *api.DeleteAllOpenPositionsParams {
	p := &api.DeleteAllOpenPositionsParams{}
	flags := cmd.Flags()
	if flags.Changed("cancel-orders") {
		p.CancelOrders = cmdutil.Bool(cmd, "cancel-orders")
	}
	return p
}

func deleteOpenPositionParamsFromFlags(cmd *cobra.Command) *api.DeleteOpenPositionParams {
	p := &api.DeleteOpenPositionParams{}
	flags := cmd.Flags()
	if flags.Changed("percentage") {
		p.Percentage = cmdutil.Str(cmd, "percentage")
	}
	if flags.Changed("qty") {
		p.Qty = cmdutil.Str(cmd, "qty")
	}
	return p
}

func deleteWatchlistByNameParamsFromFlags(cmd *cobra.Command) *api.DeleteWatchlistByNameParams {
	p := &api.DeleteWatchlistByNameParams{}
	flags := cmd.Flags()
	if flags.Changed("name") {
		p.Name = cmdutil.Str(cmd, "name")
	}
	return p
}

func fixedIncomeLatestPricesParamsFromFlags(cmd *cobra.Command) *api.FixedIncomeLatestPricesParams {
	p := &api.FixedIncomeLatestPricesParams{}
	flags := cmd.Flags()
	if flags.Changed("isins") {
		p.Isins = cmdutil.Str(cmd, "isins")
	}
	return p
}

func getAccountActivitiesParamsFromFlags(cmd *cobra.Command) *api.GetAccountActivitiesParams {
	p := &api.GetAccountActivitiesParams{}
	flags := cmd.Flags()
	if flags.Changed("activity-types") {
		p.ActivityTypes = cmdutil.Str(cmd, "activity-types")
	}
	if flags.Changed("after") {
		p.After = cmdutil.Str(cmd, "after")
	}
	if flags.Changed("category") {
		p.Category = cmdutil.Str(cmd, "category")
	}
	if flags.Changed("date") {
		p.Date = cmdutil.Str(cmd, "date")
	}
	if flags.Changed("direction") {
		p.Direction = cmdutil.Str(cmd, "direction")
	}
	if flags.Changed("page-size") {
		p.PageSize = cmdutil.Int(cmd, "page-size")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("until") {
		p.Until = cmdutil.Str(cmd, "until")
	}
	return p
}

func getAccountActivitiesByActivityTypeParamsFromFlags(cmd *cobra.Command) *api.GetAccountActivitiesByActivityTypeParams {
	p := &api.GetAccountActivitiesByActivityTypeParams{}
	flags := cmd.Flags()
	if flags.Changed("after") {
		p.After = cmdutil.Str(cmd, "after")
	}
	if flags.Changed("date") {
		p.Date = cmdutil.Str(cmd, "date")
	}
	if flags.Changed("direction") {
		p.Direction = cmdutil.Str(cmd, "direction")
	}
	if flags.Changed("page-size") {
		p.PageSize = cmdutil.Int(cmd, "page-size")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("until") {
		p.Until = cmdutil.Str(cmd, "until")
	}
	return p
}

func getAccountPortfolioHistoryParamsFromFlags(cmd *cobra.Command) *api.GetAccountPortfolioHistoryParams {
	p := &api.GetAccountPortfolioHistoryParams{}
	flags := cmd.Flags()
	if flags.Changed("cashflow-types") {
		p.CashflowTypes = cmdutil.Str(cmd, "cashflow-types")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("extended-hours") {
		p.ExtendedHours = cmdutil.Str(cmd, "extended-hours")
	}
	if flags.Changed("intraday-reporting") {
		p.IntradayReporting = cmdutil.Str(cmd, "intraday-reporting")
	}
	if flags.Changed("period") {
		p.Period = cmdutil.Str(cmd, "period")
	}
	if flags.Changed("pnl-reset") {
		p.PNLReset = cmdutil.Str(cmd, "pnl-reset")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("timeframe") {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func getAllOrdersParamsFromFlags(cmd *cobra.Command) *api.GetAllOrdersParams {
	p := &api.GetAllOrdersParams{}
	flags := cmd.Flags()
	if flags.Changed("after") {
		p.After = cmdutil.Str(cmd, "after")
	}
	if flags.Changed("after-order-id") {
		p.AfterOrderID = cmdutil.Str(cmd, "after-order-id")
	}
	if flags.Changed("asset-class") {
		p.AssetClass = cmdutil.Str(cmd, "asset-class")
	}
	if flags.Changed("before-order-id") {
		p.BeforeOrderID = cmdutil.Str(cmd, "before-order-id")
	}
	if flags.Changed("direction") {
		p.Direction = cmdutil.Str(cmd, "direction")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("nested") {
		p.Nested = cmdutil.Bool(cmd, "nested")
	}
	if flags.Changed("side") {
		p.Side = cmdutil.Str(cmd, "side")
	}
	if flags.Changed("status") {
		p.Status = cmdutil.Str(cmd, "status")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Changed("until") {
		p.Until = cmdutil.Str(cmd, "until")
	}
	return p
}

func getCryptoPerpAccountLeverageParamsFromFlags(cmd *cobra.Command) *api.GetCryptoPerpAccountLeverageParams {
	p := &api.GetCryptoPerpAccountLeverageParams{}
	flags := cmd.Flags()
	if flags.Changed("symbol") {
		p.Symbol = cmdutil.Str(cmd, "symbol")
	}
	return p
}

func getCryptoPerpTransferEstimateParamsFromFlags(cmd *cobra.Command) *api.GetCryptoPerpTransferEstimateParams {
	p := &api.GetCryptoPerpTransferEstimateParams{}
	flags := cmd.Flags()
	if flags.Changed("amount") {
		p.Amount = cmdutil.Str(cmd, "amount")
	}
	if flags.Changed("asset") {
		p.Asset = cmdutil.Str(cmd, "asset")
	}
	if flags.Changed("from-address") {
		p.FromAddress = cmdutil.Str(cmd, "from-address")
	}
	if flags.Changed("to-address") {
		p.ToAddress = cmdutil.Str(cmd, "to-address")
	}
	return p
}

func getCryptoTransferEstimateParamsFromFlags(cmd *cobra.Command) *api.GetCryptoTransferEstimateParams {
	p := &api.GetCryptoTransferEstimateParams{}
	flags := cmd.Flags()
	if flags.Changed("amount") {
		p.Amount = cmdutil.Str(cmd, "amount")
	}
	if flags.Changed("asset") {
		p.Asset = cmdutil.Str(cmd, "asset")
	}
	if flags.Changed("from-address") {
		p.FromAddress = cmdutil.Str(cmd, "from-address")
	}
	if flags.Changed("to-address") {
		p.ToAddress = cmdutil.Str(cmd, "to-address")
	}
	return p
}

func getOptionsContractsParamsFromFlags(cmd *cobra.Command) *api.GetOptionsContractsParams {
	p := &api.GetOptionsContractsParams{}
	flags := cmd.Flags()
	if flags.Changed("expiration-date") {
		p.ExpirationDate = cmdutil.Str(cmd, "expiration-date")
	}
	if flags.Changed("expiration-date-gte") {
		p.ExpirationDateGte = cmdutil.Str(cmd, "expiration-date-gte")
	}
	if flags.Changed("expiration-date-lte") {
		p.ExpirationDateLte = cmdutil.Str(cmd, "expiration-date-lte")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("ppind") {
		p.Ppind = cmdutil.Bool(cmd, "ppind")
	}
	if flags.Changed("root-symbol") {
		p.RootSymbol = cmdutil.Str(cmd, "root-symbol")
	}
	if flags.Changed("show-deliverables") {
		p.ShowDeliverables = cmdutil.Bool(cmd, "show-deliverables")
	}
	if flags.Changed("status") {
		p.Status = cmdutil.Str(cmd, "status")
	}
	if flags.Changed("strike-price-gte") {
		p.StrikePriceGte = cmdutil.Str(cmd, "strike-price-gte")
	}
	if flags.Changed("strike-price-lte") {
		p.StrikePriceLte = cmdutil.Str(cmd, "strike-price-lte")
	}
	if flags.Changed("style") {
		p.Style = cmdutil.Str(cmd, "style")
	}
	if flags.Changed("type") {
		p.Type = cmdutil.Str(cmd, "type")
	}
	if flags.Changed("underlying-symbols") {
		p.UnderlyingSymbols = cmdutil.Str(cmd, "underlying-symbols")
	}
	return p
}

func getOrderByClientOrderIDParamsFromFlags(cmd *cobra.Command) *api.GetOrderByClientOrderIDParams {
	p := &api.GetOrderByClientOrderIDParams{}
	flags := cmd.Flags()
	if flags.Changed("client-order-id") {
		p.ClientOrderID = cmdutil.Str(cmd, "client-order-id")
	}
	return p
}

func getOrderByOrderIDParamsFromFlags(cmd *cobra.Command) *api.GetOrderByOrderIDParams {
	p := &api.GetOrderByOrderIDParams{}
	flags := cmd.Flags()
	if flags.Changed("nested") {
		p.Nested = cmdutil.Bool(cmd, "nested")
	}
	return p
}

func getV2AssetsParamsFromFlags(cmd *cobra.Command) *api.GetV2AssetsParams {
	p := &api.GetV2AssetsParams{}
	flags := cmd.Flags()
	if flags.Changed("asset-class") {
		p.AssetClass = cmdutil.Str(cmd, "asset-class")
	}
	if flags.Changed("attributes") {
		p.Attributes = cmdutil.Str(cmd, "attributes")
	}
	if flags.Changed("exchange") {
		p.Exchange = cmdutil.Str(cmd, "exchange")
	}
	if flags.Changed("status") {
		p.Status = cmdutil.Str(cmd, "status")
	}
	return p
}

func getV2CorporateActionsAnnouncementsParamsFromFlags(cmd *cobra.Command) *api.GetV2CorporateActionsAnnouncementsParams {
	p := &api.GetV2CorporateActionsAnnouncementsParams{}
	flags := cmd.Flags()
	if flags.Changed("ca-types") {
		p.CaTypes = cmdutil.Str(cmd, "ca-types")
	}
	if flags.Changed("cusip") {
		p.Cusip = cmdutil.Str(cmd, "cusip")
	}
	if flags.Changed("date-type") {
		p.DateType = cmdutil.Str(cmd, "date-type")
	}
	if flags.Changed("since") {
		p.Since = cmdutil.Str(cmd, "since")
	}
	if flags.Changed("symbol") {
		p.Symbol = cmdutil.Str(cmd, "symbol")
	}
	if flags.Changed("until") {
		p.Until = cmdutil.Str(cmd, "until")
	}
	return p
}

func getWatchlistByNameParamsFromFlags(cmd *cobra.Command) *api.GetWatchlistByNameParams {
	p := &api.GetWatchlistByNameParams{}
	flags := cmd.Flags()
	if flags.Changed("name") {
		p.Name = cmdutil.Str(cmd, "name")
	}
	return p
}

func latestRatesParamsFromFlags(cmd *cobra.Command) *api.LatestRatesParams {
	p := &api.LatestRatesParams{}
	flags := cmd.Flags()
	if flags.Changed("currency-pairs") {
		p.CurrencyPairs = cmdutil.Str(cmd, "currency-pairs")
	}
	return p
}

func legacyCalendarParamsFromFlags(cmd *cobra.Command) *api.LegacyCalendarParams {
	p := &api.LegacyCalendarParams{}
	flags := cmd.Flags()
	if flags.Changed("date-type") {
		p.DateType = cmdutil.Str(cmd, "date-type")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	return p
}

func listCryptoFundingWalletsParamsFromFlags(cmd *cobra.Command) *api.ListCryptoFundingWalletsParams {
	p := &api.ListCryptoFundingWalletsParams{}
	flags := cmd.Flags()
	if flags.Changed("asset") {
		p.Asset = cmdutil.Str(cmd, "asset")
	}
	if flags.Changed("network") {
		p.Network = cmdutil.Str(cmd, "network")
	}
	return p
}

func listCryptoPerpFundingWalletsParamsFromFlags(cmd *cobra.Command) *api.ListCryptoPerpFundingWalletsParams {
	p := &api.ListCryptoPerpFundingWalletsParams{}
	flags := cmd.Flags()
	if flags.Changed("asset") {
		p.Asset = cmdutil.Str(cmd, "asset")
	}
	return p
}

func logosParamsFromFlags(cmd *cobra.Command) *api.LogosParams {
	p := &api.LogosParams{}
	flags := cmd.Flags()
	if flags.Changed("placeholder") {
		p.Placeholder = cmdutil.Bool(cmd, "placeholder")
	}
	return p
}

func mostActivesParamsFromFlags(cmd *cobra.Command) *api.MostActivesParams {
	p := &api.MostActivesParams{}
	flags := cmd.Flags()
	if flags.Changed("by") {
		p.By = cmdutil.Str(cmd, "by")
	}
	if flags.Changed("top") {
		p.Top = cmdutil.Int(cmd, "top")
	}
	return p
}

func moversParamsFromFlags(cmd *cobra.Command) *api.MoversParams {
	p := &api.MoversParams{}
	flags := cmd.Flags()
	if flags.Changed("top") {
		p.Top = cmdutil.Int(cmd, "top")
	}
	return p
}

func newsParamsFromFlags(cmd *cobra.Command) *api.NewsParams {
	p := &api.NewsParams{}
	flags := cmd.Flags()
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("exclude-contentless") {
		p.ExcludeContentless = cmdutil.Bool(cmd, "exclude-contentless")
	}
	if flags.Changed("include-content") {
		p.IncludeContent = cmdutil.Bool(cmd, "include-content")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func optionBarsParamsFromFlags(cmd *cobra.Command) *api.OptionBarsParams {
	p := &api.OptionBarsParams{}
	flags := cmd.Flags()
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Changed("timeframe") {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func optionChainParamsFromFlags(cmd *cobra.Command) *api.OptionChainParams {
	p := &api.OptionChainParams{}
	flags := cmd.Flags()
	if flags.Changed("expiration-date") {
		p.ExpirationDate = cmdutil.Str(cmd, "expiration-date")
	}
	if flags.Changed("expiration-date-gte") {
		p.ExpirationDateGte = cmdutil.Str(cmd, "expiration-date-gte")
	}
	if flags.Changed("expiration-date-lte") {
		p.ExpirationDateLte = cmdutil.Str(cmd, "expiration-date-lte")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("root-symbol") {
		p.RootSymbol = cmdutil.Str(cmd, "root-symbol")
	}
	if flags.Changed("strike-price-gte") {
		p.StrikePriceGte = cmdutil.Str(cmd, "strike-price-gte")
	}
	if flags.Changed("strike-price-lte") {
		p.StrikePriceLte = cmdutil.Str(cmd, "strike-price-lte")
	}
	if flags.Changed("type") {
		p.Type = cmdutil.Str(cmd, "type")
	}
	if flags.Changed("updated-since") {
		p.UpdatedSince = cmdutil.Str(cmd, "updated-since")
	}
	return p
}

func optionLatestQuotesParamsFromFlags(cmd *cobra.Command) *api.OptionLatestQuotesParams {
	p := &api.OptionLatestQuotesParams{}
	flags := cmd.Flags()
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func optionLatestTradesParamsFromFlags(cmd *cobra.Command) *api.OptionLatestTradesParams {
	p := &api.OptionLatestTradesParams{}
	flags := cmd.Flags()
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func optionSnapshotsParamsFromFlags(cmd *cobra.Command) *api.OptionSnapshotsParams {
	p := &api.OptionSnapshotsParams{}
	flags := cmd.Flags()
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Changed("updated-since") {
		p.UpdatedSince = cmdutil.Str(cmd, "updated-since")
	}
	return p
}

func optionTradesParamsFromFlags(cmd *cobra.Command) *api.OptionTradesParams {
	p := &api.OptionTradesParams{}
	flags := cmd.Flags()
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func ratesParamsFromFlags(cmd *cobra.Command) *api.RatesParams {
	p := &api.RatesParams{}
	flags := cmd.Flags()
	if flags.Changed("currency-pairs") {
		p.CurrencyPairs = cmdutil.Str(cmd, "currency-pairs")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("timeframe") {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func setCryptoPerpAccountLeverageParamsFromFlags(cmd *cobra.Command) *api.SetCryptoPerpAccountLeverageParams {
	p := &api.SetCryptoPerpAccountLeverageParams{}
	flags := cmd.Flags()
	if flags.Changed("leverage") {
		p.Leverage = cmdutil.Int(cmd, "leverage")
	}
	if flags.Changed("symbol") {
		p.Symbol = cmdutil.Str(cmd, "symbol")
	}
	return p
}

func stockAuctionSingleParamsFromFlags(cmd *cobra.Command) *api.StockAuctionSingleParams {
	p := &api.StockAuctionSingleParams{}
	flags := cmd.Flags()
	if flags.Changed("asof") {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	return p
}

func stockAuctionsParamsFromFlags(cmd *cobra.Command) *api.StockAuctionsParams {
	p := &api.StockAuctionsParams{}
	flags := cmd.Flags()
	if flags.Changed("asof") {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockBarSingleParamsFromFlags(cmd *cobra.Command) *api.StockBarSingleParams {
	p := &api.StockBarSingleParams{}
	flags := cmd.Flags()
	if flags.Changed("adjustment") {
		p.Adjustment = cmdutil.Str(cmd, "adjustment")
	}
	if flags.Changed("asof") {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("timeframe") {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func stockBarsParamsFromFlags(cmd *cobra.Command) *api.StockBarsParams {
	p := &api.StockBarsParams{}
	flags := cmd.Flags()
	if flags.Changed("adjustment") {
		p.Adjustment = cmdutil.Str(cmd, "adjustment")
	}
	if flags.Changed("asof") {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Changed("timeframe") {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func stockLatestBarSingleParamsFromFlags(cmd *cobra.Command) *api.StockLatestBarSingleParams {
	p := &api.StockLatestBarSingleParams{}
	flags := cmd.Flags()
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	return p
}

func stockLatestBarsParamsFromFlags(cmd *cobra.Command) *api.StockLatestBarsParams {
	p := &api.StockLatestBarsParams{}
	flags := cmd.Flags()
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockLatestQuoteSingleParamsFromFlags(cmd *cobra.Command) *api.StockLatestQuoteSingleParams {
	p := &api.StockLatestQuoteSingleParams{}
	flags := cmd.Flags()
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	return p
}

func stockLatestQuotesParamsFromFlags(cmd *cobra.Command) *api.StockLatestQuotesParams {
	p := &api.StockLatestQuotesParams{}
	flags := cmd.Flags()
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockLatestTradeSingleParamsFromFlags(cmd *cobra.Command) *api.StockLatestTradeSingleParams {
	p := &api.StockLatestTradeSingleParams{}
	flags := cmd.Flags()
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	return p
}

func stockLatestTradesParamsFromFlags(cmd *cobra.Command) *api.StockLatestTradesParams {
	p := &api.StockLatestTradesParams{}
	flags := cmd.Flags()
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockMetaConditionsParamsFromFlags(cmd *cobra.Command) *api.StockMetaConditionsParams {
	p := &api.StockMetaConditionsParams{}
	flags := cmd.Flags()
	if flags.Changed("tape") {
		p.Tape = cmdutil.Str(cmd, "tape")
	}
	return p
}

func stockQuoteSingleParamsFromFlags(cmd *cobra.Command) *api.StockQuoteSingleParams {
	p := &api.StockQuoteSingleParams{}
	flags := cmd.Flags()
	if flags.Changed("asof") {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	return p
}

func stockQuotesParamsFromFlags(cmd *cobra.Command) *api.StockQuotesParams {
	p := &api.StockQuotesParams{}
	flags := cmd.Flags()
	if flags.Changed("asof") {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockSnapshotSingleParamsFromFlags(cmd *cobra.Command) *api.StockSnapshotSingleParams {
	p := &api.StockSnapshotSingleParams{}
	flags := cmd.Flags()
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	return p
}

func stockSnapshotsParamsFromFlags(cmd *cobra.Command) *api.StockSnapshotsParams {
	p := &api.StockSnapshotsParams{}
	flags := cmd.Flags()
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockTradeSingleParamsFromFlags(cmd *cobra.Command) *api.StockTradeSingleParams {
	p := &api.StockTradeSingleParams{}
	flags := cmd.Flags()
	if flags.Changed("asof") {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	return p
}

func stockTradesParamsFromFlags(cmd *cobra.Command) *api.StockTradesParams {
	p := &api.StockTradesParams{}
	flags := cmd.Flags()
	if flags.Changed("asof") {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Changed("currency") {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Changed("end") {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Changed("feed") {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Changed("limit") {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Changed("page-token") {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Changed("sort") {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Changed("start") {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Changed("symbols") {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func updateWatchlistByNameParamsFromFlags(cmd *cobra.Command) *api.UpdateWatchlistByNameParams {
	p := &api.UpdateWatchlistByNameParams{}
	flags := cmd.Flags()
	if flags.Changed("name") {
		p.Name = cmdutil.Str(cmd, "name")
	}
	return p
}

func usCorporatesParamsFromFlags(cmd *cobra.Command) *api.UsCorporatesParams {
	p := &api.UsCorporatesParams{}
	flags := cmd.Flags()
	if flags.Changed("bond-status") {
		p.BondStatus = cmdutil.Str(cmd, "bond-status")
	}
	if flags.Changed("cusips") {
		p.Cusips = cmdutil.Str(cmd, "cusips")
	}
	if flags.Changed("isins") {
		p.Isins = cmdutil.Str(cmd, "isins")
	}
	if flags.Changed("tickers") {
		p.Tickers = cmdutil.Str(cmd, "tickers")
	}
	return p
}

func usTreasuriesParamsFromFlags(cmd *cobra.Command) *api.UsTreasuriesParams {
	p := &api.UsTreasuriesParams{}
	flags := cmd.Flags()
	if flags.Changed("bond-status") {
		p.BondStatus = cmdutil.Str(cmd, "bond-status")
	}
	if flags.Changed("cusips") {
		p.Cusips = cmdutil.Str(cmd, "cusips")
	}
	if flags.Changed("isins") {
		p.Isins = cmdutil.Str(cmd, "isins")
	}
	if flags.Changed("subtype") {
		p.Subtype = cmdutil.Str(cmd, "subtype")
	}
	return p
}

func accountConfigurationsBodyFromFlags(cmd *cobra.Command) (*api.AccountConfigurations, bool) {
	body := &api.AccountConfigurations{}
	p := cmdutil.NewPatchHelper(cmd)
	p.Bool("disable-overnight-trading", &body.DisableOvernightTrading)
	p.Str("dtbp-check", &body.DTBPCheck)
	p.Bool("fractional-trading", &body.FractionalTrading)
	p.Str("max-margin-multiplier", &body.MaxMarginMultiplier)
	p.Int("max-options-trading-level", &body.MaxOptionsTradingLevel)
	p.Bool("no-shorting", &body.NoShorting)
	p.Str("pdt-check", &body.PDTCheck)
	p.Bool("ptp-no-exception-entry", &body.PtpNoExceptionEntry)
	p.Bool("suspend-trade", &body.SuspendTrade)
	p.Str("trade-confirm-email", &body.TradeConfirmEmail)
	return body, p.AnyChanged()
}

func patchOrderRequestBodyFromFlags(cmd *cobra.Command) (*api.PatchOrderRequest, bool) {
	body := &api.PatchOrderRequest{}
	p := cmdutil.NewPatchHelper(cmd)
	p.Str("client-order-id", &body.ClientOrderID)
	p.Str("limit-price", &body.LimitPrice)
	p.Str("qty", &body.Qty)
	p.Str("stop-price", &body.StopPrice)
	p.Str("trail", &body.Trail)
	if cmdutil.Changed(cmd, "time-in-force") {
		body.TimeInForce = api.TimeInForce(cmdutil.Str(cmd, "time-in-force"))
	}
	return body, p.AnyChanged() || cmdutil.Changed(cmd, "time-in-force")
}

func updateWatchlistRequestBodyFromFlags(cmd *cobra.Command) (*api.UpdateWatchlistRequest, bool) {
	body := &api.UpdateWatchlistRequest{}
	p := cmdutil.NewPatchHelper(cmd)
	p.Str("name", &body.Name)
	return body, p.AnyChanged()
}
