// Code generated by cmd/generate; DO NOT EDIT.

package cmd

import (
	"github.com/alpacahq/cli/internal/api"
	"github.com/alpacahq/cli/internal/cmdutil"
	"github.com/spf13/cobra"
)

func accountConfigurationsBodyFromFlags(cmd *cobra.Command) (*api.AccountConfigurations, bool) {
	body := &api.AccountConfigurations{}
	p := cmdutil.NewPatchHelper(cmd)
	p.Bool("disable-overnight-trading", &body.DisableOvernightTrading)
	p.Str("dtbp-check", &body.DTBPCheck)
	p.Bool("fractional-trading", &body.FractionalTrading)
	p.Str("max-margin-multiplier", &body.MaxMarginMultiplier)
	p.Int("max-options-trading-level", &body.MaxOptionsTradingLevel)
	p.Bool("no-shorting", &body.NoShorting)
	p.Str("pdt-check", &body.PDTCheck)
	p.Bool("ptp-no-exception-entry", &body.PtpNoExceptionEntry)
	p.Bool("suspend-trade", &body.SuspendTrade)
	p.Str("trade-confirm-email", &body.TradeConfirmEmail)
	return body, p.AnyChanged()
}

func patchOrderRequestBodyFromFlags(cmd *cobra.Command) (*api.PatchOrderRequest, bool) {
	body := &api.PatchOrderRequest{}
	p := cmdutil.NewPatchHelper(cmd)
	p.Str("client-order-id", &body.ClientOrderID)
	p.Str("limit-price", &body.LimitPrice)
	p.Str("qty", &body.Qty)
	p.Str("stop-price", &body.StopPrice)
	p.Str("trail", &body.Trail)
	if cmdutil.Changed(cmd, "time-in-force") {
		body.TimeInForce = api.TimeInForce(cmdutil.Str(cmd, "time-in-force"))
	}
	return body, p.AnyChanged() || cmdutil.Changed(cmd, "time-in-force")
}

func updateWatchlistRequestBodyFromFlags(cmd *cobra.Command) (*api.UpdateWatchlistRequest, bool) {
	body := &api.UpdateWatchlistRequest{}
	p := cmdutil.NewPatchHelper(cmd)
	p.Str("name", &body.Name)
	p.Strs("symbols", &body.Symbols)
	return body, p.AnyChanged()
}
