// Code generated by cmd/generate; DO NOT EDIT.

package cmd

import (
	"github.com/alpacahq/cli/internal/api"
	"github.com/alpacahq/cli/internal/cmdutil"
	"github.com/spf13/cobra"
)

func addAssetToWatchlistByNameParamsFromFlags(cmd *cobra.Command) *api.AddAssetToWatchlistByNameParams {
	p := &api.AddAssetToWatchlistByNameParams{}
	flags := cmd.Flags()
	if flags.Lookup("name") != nil {
		p.Name = cmdutil.Str(cmd, "name")
	}
	return p
}

func calendarParamsFromFlags(cmd *cobra.Command) *api.CalendarParams {
	p := &api.CalendarParams{}
	flags := cmd.Flags()
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("timezone") != nil {
		p.Timezone = cmdutil.Str(cmd, "timezone")
	}
	return p
}

func clockParamsFromFlags(cmd *cobra.Command) *api.ClockParams {
	p := &api.ClockParams{}
	flags := cmd.Flags()
	if flags.Lookup("markets") != nil {
		p.Markets = cmdutil.Str(cmd, "markets")
	}
	if flags.Lookup("time") != nil {
		p.Time = cmdutil.Str(cmd, "time")
	}
	return p
}

func corporateActionsParamsFromFlags(cmd *cobra.Command) *api.CorporateActionsParams {
	p := &api.CorporateActionsParams{}
	flags := cmd.Flags()
	if flags.Lookup("cusips") != nil {
		p.Cusips = cmdutil.Str(cmd, "cusips")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("ids") != nil {
		p.Ids = cmdutil.Str(cmd, "ids")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Lookup("types") != nil {
		p.Types = cmdutil.Str(cmd, "types")
	}
	return p
}

func cryptoBarsParamsFromFlags(cmd *cobra.Command) *api.CryptoBarsParams {
	p := &api.CryptoBarsParams{}
	flags := cmd.Flags()
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Lookup("timeframe") != nil {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func cryptoLatestBarsParamsFromFlags(cmd *cobra.Command) *api.CryptoLatestBarsParams {
	p := &api.CryptoLatestBarsParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoLatestOrderbooksParamsFromFlags(cmd *cobra.Command) *api.CryptoLatestOrderbooksParams {
	p := &api.CryptoLatestOrderbooksParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoLatestQuotesParamsFromFlags(cmd *cobra.Command) *api.CryptoLatestQuotesParams {
	p := &api.CryptoLatestQuotesParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoLatestTradesParamsFromFlags(cmd *cobra.Command) *api.CryptoLatestTradesParams {
	p := &api.CryptoLatestTradesParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestBarsParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestBarsParams {
	p := &api.CryptoPerpLatestBarsParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestFuturesPricingParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestFuturesPricingParams {
	p := &api.CryptoPerpLatestFuturesPricingParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestOrderbooksParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestOrderbooksParams {
	p := &api.CryptoPerpLatestOrderbooksParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestQuotesParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestQuotesParams {
	p := &api.CryptoPerpLatestQuotesParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoPerpLatestTradesParamsFromFlags(cmd *cobra.Command) *api.CryptoPerpLatestTradesParams {
	p := &api.CryptoPerpLatestTradesParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoQuotesParamsFromFlags(cmd *cobra.Command) *api.CryptoQuotesParams {
	p := &api.CryptoQuotesParams{}
	flags := cmd.Flags()
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoSnapshotsParamsFromFlags(cmd *cobra.Command) *api.CryptoSnapshotsParams {
	p := &api.CryptoSnapshotsParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func cryptoTradesParamsFromFlags(cmd *cobra.Command) *api.CryptoTradesParams {
	p := &api.CryptoTradesParams{}
	flags := cmd.Flags()
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func deleteAllOpenPositionsParamsFromFlags(cmd *cobra.Command) *api.DeleteAllOpenPositionsParams {
	p := &api.DeleteAllOpenPositionsParams{}
	flags := cmd.Flags()
	if flags.Lookup("cancel-orders") != nil {
		p.CancelOrders = cmdutil.Bool(cmd, "cancel-orders")
	}
	return p
}

func deleteOpenPositionParamsFromFlags(cmd *cobra.Command) *api.DeleteOpenPositionParams {
	p := &api.DeleteOpenPositionParams{}
	flags := cmd.Flags()
	if flags.Lookup("percentage") != nil {
		p.Percentage = cmdutil.Str(cmd, "percentage")
	}
	if flags.Lookup("qty") != nil {
		p.Qty = cmdutil.Str(cmd, "qty")
	}
	return p
}

func deleteWatchlistByNameParamsFromFlags(cmd *cobra.Command) *api.DeleteWatchlistByNameParams {
	p := &api.DeleteWatchlistByNameParams{}
	flags := cmd.Flags()
	if flags.Lookup("name") != nil {
		p.Name = cmdutil.Str(cmd, "name")
	}
	return p
}

func fixedIncomeLatestPricesParamsFromFlags(cmd *cobra.Command) *api.FixedIncomeLatestPricesParams {
	p := &api.FixedIncomeLatestPricesParams{}
	flags := cmd.Flags()
	if flags.Lookup("isins") != nil {
		p.Isins = cmdutil.Str(cmd, "isins")
	}
	return p
}

func getAccountActivitiesParamsFromFlags(cmd *cobra.Command) *api.GetAccountActivitiesParams {
	p := &api.GetAccountActivitiesParams{}
	flags := cmd.Flags()
	if flags.Lookup("activity-types") != nil {
		p.ActivityTypes = cmdutil.Str(cmd, "activity-types")
	}
	if flags.Lookup("after") != nil {
		p.After = cmdutil.Str(cmd, "after")
	}
	if flags.Lookup("category") != nil {
		p.Category = cmdutil.Str(cmd, "category")
	}
	if flags.Lookup("date") != nil {
		p.Date = cmdutil.Str(cmd, "date")
	}
	if flags.Lookup("direction") != nil {
		p.Direction = cmdutil.Str(cmd, "direction")
	}
	if flags.Lookup("page-size") != nil {
		p.PageSize = cmdutil.Int(cmd, "page-size")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("until") != nil {
		p.Until = cmdutil.Str(cmd, "until")
	}
	return p
}

func getAccountActivitiesByActivityTypeParamsFromFlags(cmd *cobra.Command) *api.GetAccountActivitiesByActivityTypeParams {
	p := &api.GetAccountActivitiesByActivityTypeParams{}
	flags := cmd.Flags()
	if flags.Lookup("after") != nil {
		p.After = cmdutil.Str(cmd, "after")
	}
	if flags.Lookup("date") != nil {
		p.Date = cmdutil.Str(cmd, "date")
	}
	if flags.Lookup("direction") != nil {
		p.Direction = cmdutil.Str(cmd, "direction")
	}
	if flags.Lookup("page-size") != nil {
		p.PageSize = cmdutil.Int(cmd, "page-size")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("until") != nil {
		p.Until = cmdutil.Str(cmd, "until")
	}
	return p
}

func getAccountPortfolioHistoryParamsFromFlags(cmd *cobra.Command) *api.GetAccountPortfolioHistoryParams {
	p := &api.GetAccountPortfolioHistoryParams{}
	flags := cmd.Flags()
	if flags.Lookup("cashflow-types") != nil {
		p.CashflowTypes = cmdutil.Str(cmd, "cashflow-types")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("extended-hours") != nil {
		p.ExtendedHours = cmdutil.Str(cmd, "extended-hours")
	}
	if flags.Lookup("intraday-reporting") != nil {
		p.IntradayReporting = cmdutil.Str(cmd, "intraday-reporting")
	}
	if flags.Lookup("period") != nil {
		p.Period = cmdutil.Str(cmd, "period")
	}
	if flags.Lookup("pnl-reset") != nil {
		p.PNLReset = cmdutil.Str(cmd, "pnl-reset")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("timeframe") != nil {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func getAllOrdersParamsFromFlags(cmd *cobra.Command) *api.GetAllOrdersParams {
	p := &api.GetAllOrdersParams{}
	flags := cmd.Flags()
	if flags.Lookup("after") != nil {
		p.After = cmdutil.Str(cmd, "after")
	}
	if flags.Lookup("after-order-id") != nil {
		p.AfterOrderID = cmdutil.Str(cmd, "after-order-id")
	}
	if flags.Lookup("asset-class") != nil {
		p.AssetClass = cmdutil.Str(cmd, "asset-class")
	}
	if flags.Lookup("before-order-id") != nil {
		p.BeforeOrderID = cmdutil.Str(cmd, "before-order-id")
	}
	if flags.Lookup("direction") != nil {
		p.Direction = cmdutil.Str(cmd, "direction")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("nested") != nil {
		p.Nested = cmdutil.Bool(cmd, "nested")
	}
	if flags.Lookup("side") != nil {
		p.Side = cmdutil.Str(cmd, "side")
	}
	if flags.Lookup("status") != nil {
		p.Status = cmdutil.Str(cmd, "status")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Lookup("until") != nil {
		p.Until = cmdutil.Str(cmd, "until")
	}
	return p
}

func getCryptoPerpAccountLeverageParamsFromFlags(cmd *cobra.Command) *api.GetCryptoPerpAccountLeverageParams {
	p := &api.GetCryptoPerpAccountLeverageParams{}
	flags := cmd.Flags()
	if flags.Lookup("symbol") != nil {
		p.Symbol = cmdutil.Str(cmd, "symbol")
	}
	return p
}

func getCryptoPerpTransferEstimateParamsFromFlags(cmd *cobra.Command) *api.GetCryptoPerpTransferEstimateParams {
	p := &api.GetCryptoPerpTransferEstimateParams{}
	flags := cmd.Flags()
	if flags.Lookup("amount") != nil {
		p.Amount = cmdutil.Str(cmd, "amount")
	}
	if flags.Lookup("asset") != nil {
		p.Asset = cmdutil.Str(cmd, "asset")
	}
	if flags.Lookup("from-address") != nil {
		p.FromAddress = cmdutil.Str(cmd, "from-address")
	}
	if flags.Lookup("to-address") != nil {
		p.ToAddress = cmdutil.Str(cmd, "to-address")
	}
	return p
}

func getCryptoTransferEstimateParamsFromFlags(cmd *cobra.Command) *api.GetCryptoTransferEstimateParams {
	p := &api.GetCryptoTransferEstimateParams{}
	flags := cmd.Flags()
	if flags.Lookup("amount") != nil {
		p.Amount = cmdutil.Str(cmd, "amount")
	}
	if flags.Lookup("asset") != nil {
		p.Asset = cmdutil.Str(cmd, "asset")
	}
	if flags.Lookup("from-address") != nil {
		p.FromAddress = cmdutil.Str(cmd, "from-address")
	}
	if flags.Lookup("to-address") != nil {
		p.ToAddress = cmdutil.Str(cmd, "to-address")
	}
	return p
}

func getOptionsContractsParamsFromFlags(cmd *cobra.Command) *api.GetOptionsContractsParams {
	p := &api.GetOptionsContractsParams{}
	flags := cmd.Flags()
	if flags.Lookup("expiration-date") != nil {
		p.ExpirationDate = cmdutil.Str(cmd, "expiration-date")
	}
	if flags.Lookup("expiration-date-gte") != nil {
		p.ExpirationDateGte = cmdutil.Str(cmd, "expiration-date-gte")
	}
	if flags.Lookup("expiration-date-lte") != nil {
		p.ExpirationDateLte = cmdutil.Str(cmd, "expiration-date-lte")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("ppind") != nil {
		p.Ppind = cmdutil.Bool(cmd, "ppind")
	}
	if flags.Lookup("root-symbol") != nil {
		p.RootSymbol = cmdutil.Str(cmd, "root-symbol")
	}
	if flags.Lookup("show-deliverables") != nil {
		p.ShowDeliverables = cmdutil.Bool(cmd, "show-deliverables")
	}
	if flags.Lookup("status") != nil {
		p.Status = cmdutil.Str(cmd, "status")
	}
	if flags.Lookup("strike-price-gte") != nil {
		p.StrikePriceGte = cmdutil.Str(cmd, "strike-price-gte")
	}
	if flags.Lookup("strike-price-lte") != nil {
		p.StrikePriceLte = cmdutil.Str(cmd, "strike-price-lte")
	}
	if flags.Lookup("style") != nil {
		p.Style = cmdutil.Str(cmd, "style")
	}
	if flags.Lookup("type") != nil {
		p.Type = cmdutil.Str(cmd, "type")
	}
	if flags.Lookup("underlying-symbols") != nil {
		p.UnderlyingSymbols = cmdutil.Str(cmd, "underlying-symbols")
	}
	return p
}

func getOrderByClientOrderIDParamsFromFlags(cmd *cobra.Command) *api.GetOrderByClientOrderIDParams {
	p := &api.GetOrderByClientOrderIDParams{}
	flags := cmd.Flags()
	if flags.Lookup("client-order-id") != nil {
		p.ClientOrderID = cmdutil.Str(cmd, "client-order-id")
	}
	return p
}

func getOrderByOrderIDParamsFromFlags(cmd *cobra.Command) *api.GetOrderByOrderIDParams {
	p := &api.GetOrderByOrderIDParams{}
	flags := cmd.Flags()
	if flags.Lookup("nested") != nil {
		p.Nested = cmdutil.Bool(cmd, "nested")
	}
	return p
}

func getV2AssetsParamsFromFlags(cmd *cobra.Command) *api.GetV2AssetsParams {
	p := &api.GetV2AssetsParams{}
	flags := cmd.Flags()
	if flags.Lookup("asset-class") != nil {
		p.AssetClass = cmdutil.Str(cmd, "asset-class")
	}
	if flags.Lookup("attributes") != nil {
		p.Attributes = cmdutil.Str(cmd, "attributes")
	}
	if flags.Lookup("exchange") != nil {
		p.Exchange = cmdutil.Str(cmd, "exchange")
	}
	if flags.Lookup("status") != nil {
		p.Status = cmdutil.Str(cmd, "status")
	}
	return p
}

func getV2CorporateActionsAnnouncementsParamsFromFlags(cmd *cobra.Command) *api.GetV2CorporateActionsAnnouncementsParams {
	p := &api.GetV2CorporateActionsAnnouncementsParams{}
	flags := cmd.Flags()
	if flags.Lookup("ca-types") != nil {
		p.CaTypes = cmdutil.Str(cmd, "ca-types")
	}
	if flags.Lookup("cusip") != nil {
		p.Cusip = cmdutil.Str(cmd, "cusip")
	}
	if flags.Lookup("date-type") != nil {
		p.DateType = cmdutil.Str(cmd, "date-type")
	}
	if flags.Lookup("since") != nil {
		p.Since = cmdutil.Str(cmd, "since")
	}
	if flags.Lookup("symbol") != nil {
		p.Symbol = cmdutil.Str(cmd, "symbol")
	}
	if flags.Lookup("until") != nil {
		p.Until = cmdutil.Str(cmd, "until")
	}
	return p
}

func getWatchlistByNameParamsFromFlags(cmd *cobra.Command) *api.GetWatchlistByNameParams {
	p := &api.GetWatchlistByNameParams{}
	flags := cmd.Flags()
	if flags.Lookup("name") != nil {
		p.Name = cmdutil.Str(cmd, "name")
	}
	return p
}

func latestRatesParamsFromFlags(cmd *cobra.Command) *api.LatestRatesParams {
	p := &api.LatestRatesParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency-pairs") != nil {
		p.CurrencyPairs = cmdutil.Str(cmd, "currency-pairs")
	}
	return p
}

func legacyCalendarParamsFromFlags(cmd *cobra.Command) *api.LegacyCalendarParams {
	p := &api.LegacyCalendarParams{}
	flags := cmd.Flags()
	if flags.Lookup("date-type") != nil {
		p.DateType = cmdutil.Str(cmd, "date-type")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	return p
}

func listCryptoFundingWalletsParamsFromFlags(cmd *cobra.Command) *api.ListCryptoFundingWalletsParams {
	p := &api.ListCryptoFundingWalletsParams{}
	flags := cmd.Flags()
	if flags.Lookup("asset") != nil {
		p.Asset = cmdutil.Str(cmd, "asset")
	}
	if flags.Lookup("network") != nil {
		p.Network = cmdutil.Str(cmd, "network")
	}
	return p
}

func listCryptoPerpFundingWalletsParamsFromFlags(cmd *cobra.Command) *api.ListCryptoPerpFundingWalletsParams {
	p := &api.ListCryptoPerpFundingWalletsParams{}
	flags := cmd.Flags()
	if flags.Lookup("asset") != nil {
		p.Asset = cmdutil.Str(cmd, "asset")
	}
	return p
}

func logosParamsFromFlags(cmd *cobra.Command) *api.LogosParams {
	p := &api.LogosParams{}
	flags := cmd.Flags()
	if flags.Lookup("placeholder") != nil {
		p.Placeholder = cmdutil.Bool(cmd, "placeholder")
	}
	return p
}

func mostActivesParamsFromFlags(cmd *cobra.Command) *api.MostActivesParams {
	p := &api.MostActivesParams{}
	flags := cmd.Flags()
	if flags.Lookup("by") != nil {
		p.By = cmdutil.Str(cmd, "by")
	}
	if flags.Lookup("top") != nil {
		p.Top = cmdutil.Int(cmd, "top")
	}
	return p
}

func moversParamsFromFlags(cmd *cobra.Command) *api.MoversParams {
	p := &api.MoversParams{}
	flags := cmd.Flags()
	if flags.Lookup("top") != nil {
		p.Top = cmdutil.Int(cmd, "top")
	}
	return p
}

func newsParamsFromFlags(cmd *cobra.Command) *api.NewsParams {
	p := &api.NewsParams{}
	flags := cmd.Flags()
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("exclude-contentless") != nil {
		p.ExcludeContentless = cmdutil.Bool(cmd, "exclude-contentless")
	}
	if flags.Lookup("include-content") != nil {
		p.IncludeContent = cmdutil.Bool(cmd, "include-content")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func optionBarsParamsFromFlags(cmd *cobra.Command) *api.OptionBarsParams {
	p := &api.OptionBarsParams{}
	flags := cmd.Flags()
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Lookup("timeframe") != nil {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func optionChainParamsFromFlags(cmd *cobra.Command) *api.OptionChainParams {
	p := &api.OptionChainParams{}
	flags := cmd.Flags()
	if flags.Lookup("expiration-date") != nil {
		p.ExpirationDate = cmdutil.Str(cmd, "expiration-date")
	}
	if flags.Lookup("expiration-date-gte") != nil {
		p.ExpirationDateGte = cmdutil.Str(cmd, "expiration-date-gte")
	}
	if flags.Lookup("expiration-date-lte") != nil {
		p.ExpirationDateLte = cmdutil.Str(cmd, "expiration-date-lte")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("root-symbol") != nil {
		p.RootSymbol = cmdutil.Str(cmd, "root-symbol")
	}
	if flags.Lookup("strike-price-gte") != nil {
		p.StrikePriceGte = cmdutil.Str(cmd, "strike-price-gte")
	}
	if flags.Lookup("strike-price-lte") != nil {
		p.StrikePriceLte = cmdutil.Str(cmd, "strike-price-lte")
	}
	if flags.Lookup("type") != nil {
		p.Type = cmdutil.Str(cmd, "type")
	}
	if flags.Lookup("updated-since") != nil {
		p.UpdatedSince = cmdutil.Str(cmd, "updated-since")
	}
	return p
}

func optionLatestQuotesParamsFromFlags(cmd *cobra.Command) *api.OptionLatestQuotesParams {
	p := &api.OptionLatestQuotesParams{}
	flags := cmd.Flags()
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func optionLatestTradesParamsFromFlags(cmd *cobra.Command) *api.OptionLatestTradesParams {
	p := &api.OptionLatestTradesParams{}
	flags := cmd.Flags()
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func optionSnapshotsParamsFromFlags(cmd *cobra.Command) *api.OptionSnapshotsParams {
	p := &api.OptionSnapshotsParams{}
	flags := cmd.Flags()
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Lookup("updated-since") != nil {
		p.UpdatedSince = cmdutil.Str(cmd, "updated-since")
	}
	return p
}

func optionTradesParamsFromFlags(cmd *cobra.Command) *api.OptionTradesParams {
	p := &api.OptionTradesParams{}
	flags := cmd.Flags()
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func ratesParamsFromFlags(cmd *cobra.Command) *api.RatesParams {
	p := &api.RatesParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency-pairs") != nil {
		p.CurrencyPairs = cmdutil.Str(cmd, "currency-pairs")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("timeframe") != nil {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func setCryptoPerpAccountLeverageParamsFromFlags(cmd *cobra.Command) *api.SetCryptoPerpAccountLeverageParams {
	p := &api.SetCryptoPerpAccountLeverageParams{}
	flags := cmd.Flags()
	if flags.Lookup("leverage") != nil {
		p.Leverage = cmdutil.Int(cmd, "leverage")
	}
	if flags.Lookup("symbol") != nil {
		p.Symbol = cmdutil.Str(cmd, "symbol")
	}
	return p
}

func stockAuctionSingleParamsFromFlags(cmd *cobra.Command) *api.StockAuctionSingleParams {
	p := &api.StockAuctionSingleParams{}
	flags := cmd.Flags()
	if flags.Lookup("asof") != nil {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	return p
}

func stockAuctionsParamsFromFlags(cmd *cobra.Command) *api.StockAuctionsParams {
	p := &api.StockAuctionsParams{}
	flags := cmd.Flags()
	if flags.Lookup("asof") != nil {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockBarSingleParamsFromFlags(cmd *cobra.Command) *api.StockBarSingleParams {
	p := &api.StockBarSingleParams{}
	flags := cmd.Flags()
	if flags.Lookup("adjustment") != nil {
		p.Adjustment = cmdutil.Str(cmd, "adjustment")
	}
	if flags.Lookup("asof") != nil {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("timeframe") != nil {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func stockBarsParamsFromFlags(cmd *cobra.Command) *api.StockBarsParams {
	p := &api.StockBarsParams{}
	flags := cmd.Flags()
	if flags.Lookup("adjustment") != nil {
		p.Adjustment = cmdutil.Str(cmd, "adjustment")
	}
	if flags.Lookup("asof") != nil {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	if flags.Lookup("timeframe") != nil {
		p.Timeframe = cmdutil.Str(cmd, "timeframe")
	}
	return p
}

func stockLatestBarSingleParamsFromFlags(cmd *cobra.Command) *api.StockLatestBarSingleParams {
	p := &api.StockLatestBarSingleParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	return p
}

func stockLatestBarsParamsFromFlags(cmd *cobra.Command) *api.StockLatestBarsParams {
	p := &api.StockLatestBarsParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockLatestQuoteSingleParamsFromFlags(cmd *cobra.Command) *api.StockLatestQuoteSingleParams {
	p := &api.StockLatestQuoteSingleParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	return p
}

func stockLatestQuotesParamsFromFlags(cmd *cobra.Command) *api.StockLatestQuotesParams {
	p := &api.StockLatestQuotesParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockLatestTradeSingleParamsFromFlags(cmd *cobra.Command) *api.StockLatestTradeSingleParams {
	p := &api.StockLatestTradeSingleParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	return p
}

func stockLatestTradesParamsFromFlags(cmd *cobra.Command) *api.StockLatestTradesParams {
	p := &api.StockLatestTradesParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockMetaConditionsParamsFromFlags(cmd *cobra.Command) *api.StockMetaConditionsParams {
	p := &api.StockMetaConditionsParams{}
	flags := cmd.Flags()
	if flags.Lookup("tape") != nil {
		p.Tape = cmdutil.Str(cmd, "tape")
	}
	return p
}

func stockQuoteSingleParamsFromFlags(cmd *cobra.Command) *api.StockQuoteSingleParams {
	p := &api.StockQuoteSingleParams{}
	flags := cmd.Flags()
	if flags.Lookup("asof") != nil {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	return p
}

func stockQuotesParamsFromFlags(cmd *cobra.Command) *api.StockQuotesParams {
	p := &api.StockQuotesParams{}
	flags := cmd.Flags()
	if flags.Lookup("asof") != nil {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockSnapshotSingleParamsFromFlags(cmd *cobra.Command) *api.StockSnapshotSingleParams {
	p := &api.StockSnapshotSingleParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	return p
}

func stockSnapshotsParamsFromFlags(cmd *cobra.Command) *api.StockSnapshotsParams {
	p := &api.StockSnapshotsParams{}
	flags := cmd.Flags()
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func stockTradeSingleParamsFromFlags(cmd *cobra.Command) *api.StockTradeSingleParams {
	p := &api.StockTradeSingleParams{}
	flags := cmd.Flags()
	if flags.Lookup("asof") != nil {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	return p
}

func stockTradesParamsFromFlags(cmd *cobra.Command) *api.StockTradesParams {
	p := &api.StockTradesParams{}
	flags := cmd.Flags()
	if flags.Lookup("asof") != nil {
		p.Asof = cmdutil.Str(cmd, "asof")
	}
	if flags.Lookup("currency") != nil {
		p.Currency = cmdutil.Str(cmd, "currency")
	}
	if flags.Lookup("end") != nil {
		p.End = cmdutil.Str(cmd, "end")
	}
	if flags.Lookup("feed") != nil {
		p.Feed = cmdutil.Str(cmd, "feed")
	}
	if flags.Lookup("limit") != nil {
		p.Limit = cmdutil.Int(cmd, "limit")
	}
	if flags.Lookup("page-token") != nil {
		p.PageToken = cmdutil.Str(cmd, "page-token")
	}
	if flags.Lookup("sort") != nil {
		p.Sort = cmdutil.Str(cmd, "sort")
	}
	if flags.Lookup("start") != nil {
		p.Start = cmdutil.Str(cmd, "start")
	}
	if flags.Lookup("symbols") != nil {
		p.Symbols = cmdutil.Str(cmd, "symbols")
	}
	return p
}

func updateWatchlistByNameParamsFromFlags(cmd *cobra.Command) *api.UpdateWatchlistByNameParams {
	p := &api.UpdateWatchlistByNameParams{}
	flags := cmd.Flags()
	if flags.Lookup("name") != nil {
		p.Name = cmdutil.Str(cmd, "name")
	}
	return p
}

func usCorporatesParamsFromFlags(cmd *cobra.Command) *api.UsCorporatesParams {
	p := &api.UsCorporatesParams{}
	flags := cmd.Flags()
	if flags.Lookup("bond-status") != nil {
		p.BondStatus = cmdutil.Str(cmd, "bond-status")
	}
	if flags.Lookup("cusips") != nil {
		p.Cusips = cmdutil.Str(cmd, "cusips")
	}
	if flags.Lookup("isins") != nil {
		p.Isins = cmdutil.Str(cmd, "isins")
	}
	if flags.Lookup("tickers") != nil {
		p.Tickers = cmdutil.Str(cmd, "tickers")
	}
	return p
}

func usTreasuriesParamsFromFlags(cmd *cobra.Command) *api.UsTreasuriesParams {
	p := &api.UsTreasuriesParams{}
	flags := cmd.Flags()
	if flags.Lookup("bond-status") != nil {
		p.BondStatus = cmdutil.Str(cmd, "bond-status")
	}
	if flags.Lookup("cusips") != nil {
		p.Cusips = cmdutil.Str(cmd, "cusips")
	}
	if flags.Lookup("isins") != nil {
		p.Isins = cmdutil.Str(cmd, "isins")
	}
	if flags.Lookup("subtype") != nil {
		p.Subtype = cmdutil.Str(cmd, "subtype")
	}
	return p
}
